import type { Question } from './types';

/**
 * Wrong Answer Only deck — 200 questions.
 * Rules for every question: instantly understood, one obvious answer,
 * short enough to read out loud inside a 2.5 second clock, no special knowledge.
 * Ids are shared with `hy.ts`; add a question to both files or to neither.
 */
export const wrongAnswerEn: Question[] = [
  { id: 'wa-001', category: 'general', text: 'What color is snow?' },
  { id: 'wa-002', category: 'general', text: 'What animal says meow?' },
  { id: 'wa-003', category: 'general', text: 'How many days are in a week?' },
  { id: 'wa-004', category: 'general', text: 'What do you drink when you are thirsty?' },
  { id: 'wa-005', category: 'general', text: 'What do you put on your finger at a wedding?' },
  { id: 'wa-006', category: 'general', text: 'What do you use to call someone?' },
  { id: 'wa-007', category: 'armenia', text: 'What country is Yerevan in?' },
  { id: 'wa-008', category: 'general', text: 'What do cows give us?' },
  { id: 'wa-009', category: 'general', text: 'What do you put on before your shoes?' },
  { id: 'wa-010', category: 'general', text: 'What do you open a door with?' },
  { id: 'wa-011', category: 'general', text: 'How many legs does a dog have?' },
  { id: 'wa-012', category: 'general', text: 'What color is the sky on a clear day?' },
  { id: 'wa-013', category: 'general', text: 'What do you cut bread with?' },
  { id: 'wa-014', category: 'general', text: 'How much is two plus two?' },
  { id: 'wa-015', category: 'general', text: 'Where do fish live?' },
  { id: 'wa-016', category: 'general', text: 'What do you sleep on?' },
  { id: 'wa-017', category: 'general', text: 'Which season comes after winter?' },
  { id: 'wa-018', category: 'general', text: 'What do bees make?' },
  { id: 'wa-019', category: 'general', text: 'What color is a banana?' },
  { id: 'wa-020', category: 'general', text: 'How many fingers are on one hand?' },
  { id: 'wa-021', category: 'general', text: 'What do you put toothpaste on?' },
  { id: 'wa-022', category: 'general', text: 'Where do you keep milk so it stays cold?' },
  { id: 'wa-023', category: 'general', text: 'What falls from the sky when it rains?' },
  { id: 'wa-024', category: 'general', text: 'What do you wear on your head?' },
  { id: 'wa-025', category: 'general', text: 'Which animal barks?' },
  { id: 'wa-026', category: 'general', text: 'What do you look in to see yourself?' },
  { id: 'wa-027', category: 'general', text: 'What do birds have that lets them fly?' },
  { id: 'wa-028', category: 'armenia', text: 'What is the capital of Armenia?' },
  { id: 'wa-029', category: 'general', text: 'How many wheels does a car have?' },
  { id: 'wa-030', category: 'general', text: 'What do you sharpen a pencil with?' },
  { id: 'wa-031', category: 'general', text: 'What color is grass?' },
  { id: 'wa-032', category: 'food', text: 'What do you eat soup with?' },
  { id: 'wa-033', category: 'general', text: 'Which month comes after January?' },
  { id: 'wa-034', category: 'general', text: 'What do you charge your phone with?' },
  { id: 'wa-035', category: 'general', text: 'What do chickens lay?' },
  { id: 'wa-036', category: 'general', text: 'What is frozen water called?' },
  { id: 'wa-037', category: 'general', text: 'How many minutes are in an hour?' },
  { id: 'wa-038', category: 'general', text: 'What do you turn on to see in the dark?' },
  { id: 'wa-039', category: 'general', text: 'What do you put on your hands when it is cold?' },
  { id: 'wa-040', category: 'general', text: 'Which animal has a trunk?' },
  { id: 'wa-041', category: 'general', text: 'What do you sit on?' },
  { id: 'wa-042', category: 'general', text: 'What is the opposite of hot?' },
  { id: 'wa-043', category: 'general', text: 'What do you dry yourself with after a shower?' },
  { id: 'wa-044', category: 'food', text: 'What color is a tomato?' },
  { id: 'wa-045', category: 'general', text: 'What rings in the morning to wake you up?' },
  { id: 'wa-046', category: 'general', text: 'What do you comb your hair with?' },
  { id: 'wa-047', category: 'food', text: 'What do you put in coffee to make it sweet?' },
  { id: 'wa-048', category: 'general', text: 'What do you wash your hands with?' },
  { id: 'wa-049', category: 'general', text: 'Which meal do you eat in the morning?' },
  { id: 'wa-050', category: 'general', text: 'What do you say when you meet someone?' },

  // Everyday life and common objects.
  { id: 'wa-051', category: 'general', text: 'What do you cut paper with?' },
  { id: 'wa-052', category: 'general', text: 'What do you open over your head when it rains?' },
  { id: 'wa-053', category: 'general', text: 'What do you sweep the floor with?' },
  { id: 'wa-054', category: 'general', text: 'What do you put under your head when you sleep?' },
  { id: 'wa-055', category: 'general', text: 'What do you cover yourself with in bed?' },
  { id: 'wa-056', category: 'general', text: 'What do you keep your money in?' },
  { id: 'wa-057', category: 'general', text: 'What do you carry your books to school in?' },
  { id: 'wa-058', category: 'general', text: 'What do you iron clothes with?' },
  { id: 'wa-059', category: 'general', text: 'What do you put food on at the table?' },
  { id: 'wa-060', category: 'general', text: 'What do you wear to see better?' },
  { id: 'wa-061', category: 'general', text: 'What do you wrap around your neck in winter?' },
  { id: 'wa-062', category: 'general', text: 'Where do you throw trash?' },
  { id: 'wa-063', category: 'general', text: 'What do you blow out on a birthday cake?' },
  { id: 'wa-064', category: 'general', text: 'What do you sit at to eat?' },
  { id: 'wa-065', category: 'general', text: 'What do you wash your hair with?' },
  { id: 'wa-066', category: 'general', text: 'Who do you go to when you are sick?' },
  { id: 'wa-067', category: 'general', text: 'Who teaches at school?' },
  { id: 'wa-068', category: 'general', text: 'Who puts out fires?' },
  { id: 'wa-069', category: 'general', text: 'What do you ring at someone’s door?' },
  { id: 'wa-070', category: 'general', text: 'What do you stick on a cut?' },
  { id: 'wa-071', category: 'general', text: 'What do you pour tea into?' },

  // Body, actions and senses.
  { id: 'wa-072', category: 'general', text: 'What do you hear with?' },
  { id: 'wa-073', category: 'general', text: 'What do you smell with?' },
  { id: 'wa-074', category: 'general', text: 'What do you taste with?' },
  { id: 'wa-075', category: 'general', text: 'What grows on your head?' },
  { id: 'wa-076', category: 'general', text: 'What beats in your chest?' },
  { id: 'wa-077', category: 'general', text: 'What do you breathe?' },
  { id: 'wa-078', category: 'general', text: 'What do you do when you are tired?' },
  { id: 'wa-079', category: 'general', text: 'What do you do when you are hungry?' },
  { id: 'wa-080', category: 'general', text: 'What comes out of your eyes when you cry?' },
  { id: 'wa-081', category: 'general', text: 'What do you close when you sleep?' },
  { id: 'wa-082', category: 'general', text: 'Where do you wear a ring?' },
  { id: 'wa-083', category: 'general', text: 'Where do you wear a watch?' },
  { id: 'wa-084', category: 'general', text: 'What do you do when something is funny?' },
  { id: 'wa-085', category: 'general', text: 'What do you say when someone sneezes?' },
  { id: 'wa-086', category: 'general', text: 'What do you kick a ball with?' },
  { id: 'wa-087', category: 'general', text: 'What is at the tip of your fingers?' },
  { id: 'wa-088', category: 'general', text: 'What color is blood?' },
  { id: 'wa-089', category: 'general', text: 'Where does your arm bend?' },

  // Animals and nature.
  { id: 'wa-090', category: 'general', text: 'Which animal has a long neck?' },
  { id: 'wa-091', category: 'general', text: 'Who is the king of the animals?' },
  { id: 'wa-092', category: 'general', text: 'Which animal croaks?' },
  { id: 'wa-093', category: 'general', text: 'Which animal loves bananas?' },
  { id: 'wa-094', category: 'general', text: 'Which animal gives us wool?' },
  { id: 'wa-095', category: 'general', text: 'What spins a web?' },
  { id: 'wa-096', category: 'general', text: 'What color is a crow?' },
  { id: 'wa-097', category: 'general', text: 'What do cats catch?' },
  { id: 'wa-098', category: 'general', text: 'In which season do leaves fall?' },
  { id: 'wa-099', category: 'general', text: 'Which animal says cock-a-doodle-doo?' },
  { id: 'wa-100', category: 'general', text: 'Which animal has a hump?' },
  { id: 'wa-101', category: 'general', text: 'What appears in the sky after rain?' },
  { id: 'wa-102', category: 'general', text: 'What do you hear after lightning?' },

  // Food and drinks.
  { id: 'wa-103', category: 'food', text: 'What do you cut on your birthday?' },
  { id: 'wa-104', category: 'food', text: 'What is bread made from?' },
  { id: 'wa-105', category: 'food', text: 'What is the yellow part of an egg called?' },
  { id: 'wa-106', category: 'food', text: 'What does a lemon taste like?' },
  { id: 'wa-107', category: 'food', text: 'What do you add to food to make it salty?' },
  { id: 'wa-108', category: 'food', text: 'What is cheese made from?' },
  { id: 'wa-109', category: 'food', text: 'Which vegetable makes you cry when you cut it?' },
  { id: 'wa-110', category: 'food', text: 'What do rabbits love to eat?' },
  { id: 'wa-111', category: 'food', text: 'What are fries made from?' },
  { id: 'wa-112', category: 'food', text: 'Which fruit is full of red seeds?' },
  { id: 'wa-113', category: 'food', text: 'What is popcorn made from?' },
  { id: 'wa-114', category: 'funny', text: 'Is ice cream hot or cold?' },
  { id: 'wa-115', category: 'food', text: 'What happens to ice cream in the sun?' },
  { id: 'wa-116', category: 'food', text: 'What do you eat pasta with?' },
  { id: 'wa-117', category: 'food', text: 'What is a watermelon mostly made of?' },
  { id: 'wa-118', category: 'food', text: 'What is an omelette made from?' },
  { id: 'wa-119', category: 'food', text: 'What does sugar taste like?' },
  { id: 'wa-120', category: 'food', text: 'What do grapes become when they dry?' },
  { id: 'wa-121', category: 'food', text: 'What do you spread butter on?' },

  // Numbers, time and basic concepts.
  { id: 'wa-122', category: 'general', text: 'How many months are in a year?' },
  { id: 'wa-123', category: 'general', text: 'How many hours are in a day?' },
  { id: 'wa-124', category: 'general', text: 'What day comes after Monday?' },
  { id: 'wa-125', category: 'general', text: 'What is the last month of the year?' },
  { id: 'wa-126', category: 'general', text: 'What number comes after nine?' },
  { id: 'wa-127', category: 'general', text: 'What is half of ten?' },
  { id: 'wa-128', category: 'general', text: 'What is the opposite of big?' },
  { id: 'wa-129', category: 'general', text: 'What is the opposite of day?' },
  { id: 'wa-130', category: 'general', text: 'What is the opposite of up?' },
  { id: 'wa-131', category: 'funny', text: 'Which is bigger, five or three?' },
  { id: 'wa-132', category: 'general', text: 'Which season is the hottest?' },
  { id: 'wa-133', category: 'general', text: 'How many sides does a triangle have?' },
  { id: 'wa-134', category: 'general', text: 'What shape is a ball?' },

  // Simple geography and world knowledge.
  { id: 'wa-135', category: 'general', text: 'What planet do we live on?' },
  { id: 'wa-136', category: 'general', text: 'What shines in the sky during the day?' },
  { id: 'wa-137', category: 'general', text: 'What do you hit a nail with?' },
  { id: 'wa-138', category: 'general', text: 'How many eyes do you have?' },
  { id: 'wa-139', category: 'general', text: 'Which animal loves honey?' },
  { id: 'wa-140', category: 'general', text: 'What do you open to let fresh air in?' },
  { id: 'wa-141', category: 'general', text: 'What do you blow up to make it big?' },
  { id: 'wa-142', category: 'general', text: 'What do you hang over a window?' },
  { id: 'wa-143', category: 'food', text: 'What does hot pepper do to your mouth?' },
  { id: 'wa-144', category: 'funny', text: 'Is it cold or hot at the North Pole?' },
  { id: 'wa-145', category: 'general', text: 'Is sea water salty or sweet?' },
  { id: 'wa-146', category: 'general', text: 'What do you chew with?' },
  { id: 'wa-147', category: 'general', text: 'What does a driver turn to steer the car?' },
  { id: 'wa-148', category: 'general', text: 'What do you wear on your head on a motorcycle?' },
  { id: 'wa-149', category: 'general', text: 'What do you erase pencil marks with?' },
  { id: 'wa-150', category: 'funny', text: 'Which is bigger, a city or a village?' },
  { id: 'wa-151', category: 'general', text: 'What language do they speak in England?' },
  { id: 'wa-152', category: 'food', text: 'What is wine made from?' },
  { id: 'wa-153', category: 'general', text: 'Where does water come out of in the kitchen?' },

  // Armenia — things every Armenian at the table knows without thinking.
  { id: 'wa-154', category: 'armenia', text: 'Who brings the presents at New Year in Armenia?' },
  { id: 'wa-155', category: 'armenia', text: 'What is the biggest lake in Armenia?' },
  { id: 'wa-156', category: 'armenia', text: 'Does it snow in Armenia in winter?' },
  { id: 'wa-157', category: 'armenia', text: 'What is the first letter of the Armenian alphabet?' },
  { id: 'wa-158', category: 'armenia', text: 'What bread is baked in a tonir?' },
  { id: 'wa-159', category: 'armenia', text: 'Is a duduk a musical instrument or food?' },
  { id: 'wa-160', category: 'yerevan', text: 'What do you call someone who lives in Yerevan?' },
  { id: 'wa-161', category: 'armenia', text: 'How many colors are on the Armenian flag?' },
  { id: 'wa-162', category: 'armenia', text: 'In which season do Armenians eat khash?' },
  { id: 'wa-163', category: 'armenia', text: 'What is Armenian money called?' },
  { id: 'wa-164', category: 'general', text: 'Which animal has long ears and hops?' },
  { id: 'wa-165', category: 'armenia', text: 'What is meat grilled on skewers called?' },
  { id: 'wa-166', category: 'general', text: 'What do you say on someone’s birthday?' },
  { id: 'wa-167', category: 'armenia', text: 'What do you wrap in grape leaves?' },
  { id: 'wa-168', category: 'armenia', text: 'Is lavash thin or thick?' },
  { id: 'wa-169', category: 'armenia', text: 'What do people pour on each other at Vardavar?' },
  { id: 'wa-170', category: 'funny', text: 'Does Armenia have a sea?' },
  { id: 'wa-171', category: 'general', text: 'What do you do in a swimming pool?' },
  { id: 'wa-172', category: 'armenia', text: 'What do you dye at Easter?' },
  { id: 'wa-173', category: 'armenia', text: 'Which mountain is Armenia known for?' },
  { id: 'wa-174', category: 'general', text: 'What do you hang on the wall to see the time?' },
  { id: 'wa-175', category: 'general', text: 'What do you clap with?' },
  { id: 'wa-176', category: 'yerevan', text: 'What color city is Yerevan called?' },
  { id: 'wa-177', category: 'general', text: 'What do you tie your shoes with?' },

  // Technology, household and transport.
  { id: 'wa-178', category: 'general', text: 'What do you travel through the sky in?' },
  { id: 'wa-179', category: 'general', text: 'What runs on rails?' },
  { id: 'wa-180', category: 'general', text: 'What has two wheels and pedals?' },
  { id: 'wa-181', category: 'general', text: 'Which traffic light color means stop?' },
  { id: 'wa-182', category: 'general', text: 'What do you heat food up in quickly?' },
  { id: 'wa-183', category: 'general', text: 'What machine washes your clothes?' },
  { id: 'wa-184', category: 'general', text: 'What do you put on your ears to listen to music?' },
  { id: 'wa-185', category: 'general', text: 'What do you change TV channels with?' },
  { id: 'wa-186', category: 'general', text: 'What takes you up in a tall building?' },
  { id: 'wa-187', category: 'general', text: 'Which vehicle takes sick people to the hospital?' },
  { id: 'wa-188', category: 'general', text: 'Where do planes land?' },

  // Trick-style prompts — the answer is in the room.
  { id: 'wa-189', category: 'funny', text: 'What language are you speaking right now?' },
  { id: 'wa-190', category: 'funny', text: 'How many noses do you have?' },
  { id: 'wa-191', category: 'funny', text: 'What is your name?' },
  { id: 'wa-192', category: 'funny', text: 'Is fire hot or cold?' },
  { id: 'wa-193', category: 'funny', text: 'Does a fish have legs?' },
  { id: 'wa-194', category: 'funny', text: 'Can pigs fly?' },
  { id: 'wa-195', category: 'funny', text: 'What do you say when you answer the phone?' },
  { id: 'wa-196', category: 'funny', text: 'What is the opposite of yes?' },
  { id: 'wa-197', category: 'funny', text: 'Which is louder, a whisper or a shout?' },
  { id: 'wa-198', category: 'funny', text: 'Which is bigger, an elephant or a mouse?' },
  { id: 'wa-199', category: 'funny', text: 'What color is a red apple?' },
  { id: 'wa-200', category: 'funny', text: 'Which is faster, a car or a bicycle?' },
];
