import type { Question } from './types';

/**
 * V1 starter set — 50 questions.
 * Rules for every question: instantly understood, one obvious answer,
 * short enough to read out loud in two seconds, no special knowledge.
 */
export const wrongAnswerEn: Question[] = [
  { id: 'wa-001', category: 'general', text: 'What color is snow?' },
  { id: 'wa-002', category: 'general', text: 'What animal says meow?' },
  { id: 'wa-003', category: 'general', text: 'How many days are in a week?' },
  { id: 'wa-004', category: 'general', text: 'What do you drink when you are thirsty?' },
  { id: 'wa-005', category: 'general', text: 'Where does the sun rise?' },
  { id: 'wa-006', category: 'general', text: 'What do you use to call someone?' },
  { id: 'wa-007', category: 'armenia', text: 'What country is Yerevan in?' },
  { id: 'wa-008', category: 'general', text: 'What do cows give us?' },
  { id: 'wa-009', category: 'general', text: 'What do you wear on your feet?' },
  { id: 'wa-010', category: 'general', text: 'What do you open a door with?' },
  { id: 'wa-011', category: 'general', text: 'How many legs does a dog have?' },
  { id: 'wa-012', category: 'general', text: 'What color is the sky on a clear day?' },
  { id: 'wa-013', category: 'general', text: 'What do you cut bread with?' },
  { id: 'wa-014', category: 'general', text: 'How much is two plus two?' },
  { id: 'wa-015', category: 'general', text: 'Where do fish live?' },
  { id: 'wa-016', category: 'general', text: 'What do you sleep on?' },
  { id: 'wa-017', category: 'general', text: 'Which season comes after winter?' },
  { id: 'wa-018', category: 'general', text: 'What do bees make?' },
  { id: 'wa-019', category: 'general', text: 'What color is a banana?' },
  { id: 'wa-020', category: 'general', text: 'How many fingers are on one hand?' },
  { id: 'wa-021', category: 'general', text: 'What do you brush your teeth with?' },
  { id: 'wa-022', category: 'general', text: 'Where do you keep milk so it stays cold?' },
  { id: 'wa-023', category: 'general', text: 'What falls from the sky when it rains?' },
  { id: 'wa-024', category: 'general', text: 'What do you wear on your head?' },
  { id: 'wa-025', category: 'general', text: 'Which animal barks?' },
  { id: 'wa-026', category: 'general', text: 'What do you read?' },
  { id: 'wa-027', category: 'general', text: 'What do birds have that lets them fly?' },
  { id: 'wa-028', category: 'armenia', text: 'What is the capital of Armenia?' },
  { id: 'wa-029', category: 'general', text: 'How many wheels does a car have?' },
  { id: 'wa-030', category: 'general', text: 'What do you write with?' },
  { id: 'wa-031', category: 'general', text: 'What color is grass?' },
  { id: 'wa-032', category: 'food', text: 'What do you eat soup with?' },
  { id: 'wa-033', category: 'general', text: 'Which month comes after January?' },
  { id: 'wa-034', category: 'general', text: 'What do you watch movies on?' },
  { id: 'wa-035', category: 'general', text: 'What do chickens lay?' },
  { id: 'wa-036', category: 'general', text: 'What is frozen water called?' },
  { id: 'wa-037', category: 'general', text: 'How many minutes are in an hour?' },
  { id: 'wa-038', category: 'general', text: 'What do you turn on to see in the dark?' },
  { id: 'wa-039', category: 'general', text: 'What do you put on your hands when it is cold?' },
  { id: 'wa-040', category: 'general', text: 'Which animal has a trunk?' },
  { id: 'wa-041', category: 'general', text: 'What do you sit on?' },
  { id: 'wa-042', category: 'general', text: 'What is the opposite of hot?' },
  { id: 'wa-043', category: 'general', text: 'What do you dry yourself with after a shower?' },
  { id: 'wa-044', category: 'food', text: 'What color is a tomato?' },
  { id: 'wa-045', category: 'general', text: 'What do you take photos with?' },
  { id: 'wa-046', category: 'general', text: 'What do you comb your hair with?' },
  { id: 'wa-047', category: 'food', text: 'What do you put in coffee to make it sweet?' },
  { id: 'wa-048', category: 'general', text: 'What do you wash your hands with?' },
  { id: 'wa-049', category: 'general', text: 'Which meal do you eat in the morning?' },
  { id: 'wa-050', category: 'general', text: 'What do you say when you meet someone?' },
];
