import type { Question } from './types';

/**
 * V1 starter set — 50 questions, paired 1:1 with the English ids.
 * Wording is deliberately spoken-Armenian, the way it would be read out at a table.
 */
export const wrongAnswerHy: Question[] = [
  { id: 'wa-001', category: 'general', text: 'Ի՞նչ գույնի է ձյունը։' },
  { id: 'wa-002', category: 'general', text: 'Ո՞ր կենդանին է մյաու անում։' },
  { id: 'wa-003', category: 'general', text: 'Շաբաթը քանի՞ օր ունի։' },
  { id: 'wa-004', category: 'general', text: 'Ի՞նչ ես խմում, երբ ծարավ ես։' },
  { id: 'wa-005', category: 'general', text: 'Որտեղի՞ց է ծագում արևը։' },
  { id: 'wa-006', category: 'general', text: 'Ինչո՞վ ես զանգում մարդուն։' },
  { id: 'wa-007', category: 'armenia', text: 'Ո՞ր երկրում է Երևանը։' },
  { id: 'wa-008', category: 'general', text: 'Կովը ի՞նչ է տալիս։' },
  { id: 'wa-009', category: 'general', text: 'Ի՞նչ ես հագնում ոտքերիդ։' },
  { id: 'wa-010', category: 'general', text: 'Ինչո՞վ ես դուռը բացում։' },
  { id: 'wa-011', category: 'general', text: 'Շունը քանի՞ ոտք ունի։' },
  { id: 'wa-012', category: 'general', text: 'Պարզ օրը ի՞նչ գույնի է երկինքը։' },
  { id: 'wa-013', category: 'general', text: 'Ինչո՞վ ես հացը կտրում։' },
  { id: 'wa-014', category: 'general', text: 'Երկու գումարած երկու քանի՞ է։' },
  { id: 'wa-015', category: 'general', text: 'Որտե՞ղ են ապրում ձկները։' },
  { id: 'wa-016', category: 'general', text: 'Ինչի՞ վրա ես քնում։' },
  { id: 'wa-017', category: 'general', text: 'Ձմռանից հետո ո՞ր եղանակն է գալիս։' },
  { id: 'wa-018', category: 'general', text: 'Մեղուները ի՞նչ են պատրաստում։' },
  { id: 'wa-019', category: 'general', text: 'Ի՞նչ գույնի է բանանը։' },
  { id: 'wa-020', category: 'general', text: 'Մի ձեռքը քանի՞ մատ ունի։' },
  { id: 'wa-021', category: 'general', text: 'Ինչո՞վ ես ատամներդ լվանում։' },
  { id: 'wa-022', category: 'general', text: 'Որտե՞ղ ես կաթը պահում, որ սառը մնա։' },
  { id: 'wa-023', category: 'general', text: 'Անձրևի ժամանակ երկնքից ի՞նչ է թափվում։' },
  { id: 'wa-024', category: 'general', text: 'Ի՞նչ ես դնում գլխիդ։' },
  { id: 'wa-025', category: 'general', text: 'Ո՞ր կենդանին է հաչում։' },
  { id: 'wa-026', category: 'general', text: 'Ի՞նչ ես կարդում։' },
  { id: 'wa-027', category: 'general', text: 'Թռչուններն ի՞նչ ունեն, որ թռչում են։' },
  { id: 'wa-028', category: 'armenia', text: 'Ո՞րն է Հայաստանի մայրաքաղաքը։' },
  { id: 'wa-029', category: 'general', text: 'Մեքենան քանի՞ անիվ ունի։' },
  { id: 'wa-030', category: 'general', text: 'Ինչո՞վ ես գրում։' },
  { id: 'wa-031', category: 'general', text: 'Ի՞նչ գույնի է խոտը։' },
  { id: 'wa-032', category: 'food', text: 'Ինչո՞վ ես ապուր ուտում։' },
  { id: 'wa-033', category: 'general', text: 'Հունվարից հետո ո՞ր ամիսն է գալիս։' },
  { id: 'wa-034', category: 'general', text: 'Ինչի՞ վրա ես ֆիլմ նայում։' },
  { id: 'wa-035', category: 'general', text: 'Հավը ի՞նչ է ածում։' },
  { id: 'wa-036', category: 'general', text: 'Սառած ջուրն ինչպե՞ս է կոչվում։' },
  { id: 'wa-037', category: 'general', text: 'Մեկ ժամը քանի՞ րոպե է։' },
  { id: 'wa-038', category: 'general', text: 'Ի՞նչ ես վառում, որ մթության մեջ տեսնես։' },
  { id: 'wa-039', category: 'general', text: 'Ցրտին ի՞նչ ես հագնում ձեռքերիդ։' },
  { id: 'wa-040', category: 'general', text: 'Ո՞ր կենդանին ունի կնճիթ։' },
  { id: 'wa-041', category: 'general', text: 'Ինչի՞ վրա ես նստում։' },
  { id: 'wa-042', category: 'general', text: 'Ի՞նչն է տաքի հակառակը։' },
  { id: 'wa-043', category: 'general', text: 'Ինչո՞վ ես չորանում լոգանքից հետո։' },
  { id: 'wa-044', category: 'food', text: 'Ի՞նչ գույնի է լոլիկը։' },
  { id: 'wa-045', category: 'general', text: 'Ինչո՞վ ես լուսանկարում։' },
  { id: 'wa-046', category: 'general', text: 'Ինչո՞վ ես մազերդ սանրում։' },
  { id: 'wa-047', category: 'food', text: 'Ի՞նչ ես գցում սուրճի մեջ, որ քաղցր լինի։' },
  { id: 'wa-048', category: 'general', text: 'Ինչո՞վ ես ձեռքերդ լվանում։' },
  { id: 'wa-049', category: 'general', text: 'Առավոտյան ո՞ր կերակուրն ես ուտում։' },
  { id: 'wa-050', category: 'general', text: 'Ի՞նչ ես ասում, երբ մեկին հանդիպում ես։' },
];
