import type { Question } from './types';

/**
 * Wrong Answer Only deck — 200 questions, paired 1:1 with the English ids.
 * Wording is deliberately spoken Eastern Armenian, the way it would be read out at a table:
 * short, one obvious answer, readable on a phone inside a 2.5 second clock.
 */
export const wrongAnswerHy: Question[] = [
  { id: 'wa-001', category: 'general', text: 'Ի՞նչ գույնի է ձյունը։' },
  { id: 'wa-002', category: 'general', text: 'Ո՞ր կենդանին է մյաու անում։' },
  { id: 'wa-003', category: 'general', text: 'Շաբաթը քանի՞ օր ունի։' },
  { id: 'wa-004', category: 'general', text: 'Ի՞նչ ես խմում, երբ ծարավ ես։' },
  { id: 'wa-005', category: 'general', text: 'Հարսանիքին մատիդ ի՞նչ ես դնում։' },
  { id: 'wa-006', category: 'general', text: 'Ինչո՞վ ես զանգում։' },
  { id: 'wa-007', category: 'armenia', text: 'Ո՞ր երկրում է Երևանը։' },
  { id: 'wa-008', category: 'general', text: 'Կովն ի՞նչ է տալիս։' },
  { id: 'wa-009', category: 'general', text: 'Կոշիկից առաջ ի՞նչ ես հագնում։' },
  { id: 'wa-010', category: 'general', text: 'Ինչո՞վ ես դուռը բացում։' },
  { id: 'wa-011', category: 'general', text: 'Շունը քանի՞ ոտք ունի։' },
  { id: 'wa-012', category: 'general', text: 'Պարզ օրն ի՞նչ գույնի է երկինքը։' },
  { id: 'wa-013', category: 'general', text: 'Ինչո՞վ ես հացը կտրում։' },
  { id: 'wa-014', category: 'general', text: 'Երկու գումարած երկու քանի՞ է։' },
  { id: 'wa-015', category: 'general', text: 'Որտե՞ղ են ապրում ձկները։' },
  { id: 'wa-016', category: 'general', text: 'Ինչի՞ վրա ես քնում։' },
  { id: 'wa-017', category: 'general', text: 'Ձմռանից հետո ո՞ր եղանակն է գալիս։' },
  { id: 'wa-018', category: 'general', text: 'Մեղուներն ի՞նչ են սարքում։' },
  { id: 'wa-019', category: 'general', text: 'Ի՞նչ գույնի է բանանը։' },
  { id: 'wa-020', category: 'general', text: 'Մի ձեռքը քանի՞ մատ ունի։' },
  { id: 'wa-021', category: 'general', text: 'Ատամի մածուկն ինչի՞ վրա ես քսում։' },
  { id: 'wa-022', category: 'general', text: 'Որտե՞ղ ես կաթը պահում, որ սառը մնա։' },
  { id: 'wa-023', category: 'general', text: 'Անձրևի ժամանակ երկնքից ի՞նչ է թափվում։' },
  { id: 'wa-024', category: 'general', text: 'Ի՞նչ ես դնում գլխիդ։' },
  { id: 'wa-025', category: 'general', text: 'Ո՞ր կենդանին է հաչում։' },
  { id: 'wa-026', category: 'general', text: 'Ինչի՞ մեջ ես քեզ նայում։' },
  { id: 'wa-027', category: 'general', text: 'Թռչուններն ի՞նչ ունեն, որ թռչում են։' },
  { id: 'wa-028', category: 'armenia', text: 'Ո՞րն է Հայաստանի մայրաքաղաքը։' },
  { id: 'wa-029', category: 'general', text: 'Մեքենան քանի՞ անիվ ունի։' },
  { id: 'wa-030', category: 'general', text: 'Մատիտն ինչո՞վ ես սրում։' },
  { id: 'wa-031', category: 'general', text: 'Ի՞նչ գույնի է խոտը։' },
  { id: 'wa-032', category: 'food', text: 'Ինչո՞վ ես ապուր ուտում։' },
  { id: 'wa-033', category: 'general', text: 'Հունվարից հետո ո՞ր ամիսն է գալիս։' },
  { id: 'wa-034', category: 'general', text: 'Ինչո՞վ ես հեռախոսդ լիցքավորում։' },
  { id: 'wa-035', category: 'general', text: 'Հավն ի՞նչ է ածում։' },
  { id: 'wa-036', category: 'general', text: 'Սառած ջուրն ինչպե՞ս է կոչվում։' },
  { id: 'wa-037', category: 'general', text: 'Մեկ ժամը քանի՞ րոպե է։' },
  { id: 'wa-038', category: 'general', text: 'Ի՞նչ ես վառում, որ մթության մեջ տեսնես։' },
  { id: 'wa-039', category: 'general', text: 'Ցրտին ի՞նչ ես հագնում ձեռքերիդ։' },
  { id: 'wa-040', category: 'general', text: 'Ո՞ր կենդանին ունի կնճիթ։' },
  { id: 'wa-041', category: 'general', text: 'Ինչի՞ վրա ես նստում։' },
  { id: 'wa-042', category: 'general', text: 'Ի՞նչն է տաքի հակառակը։' },
  { id: 'wa-043', category: 'general', text: 'Լոգանքից հետո ինչո՞վ ես սրբվում։' },
  { id: 'wa-044', category: 'food', text: 'Ի՞նչ գույնի է լոլիկը։' },
  { id: 'wa-045', category: 'general', text: 'Առավոտյան ի՞նչ է զնգում, որ արթնանաս։' },
  { id: 'wa-046', category: 'general', text: 'Ինչո՞վ ես մազերդ սանրում։' },
  { id: 'wa-047', category: 'food', text: 'Ի՞նչ ես գցում սուրճի մեջ, որ քաղցր լինի։' },
  { id: 'wa-048', category: 'general', text: 'Ինչո՞վ ես ձեռքերդ լվանում։' },
  { id: 'wa-049', category: 'general', text: 'Առավոտյան ո՞ր կերակուրն ես ուտում։' },
  { id: 'wa-050', category: 'general', text: 'Ի՞նչ ես ասում, երբ մեկին հանդիպում ես։' },

  // Everyday life and common objects.
  { id: 'wa-051', category: 'general', text: 'Ինչո՞վ ես թուղթը կտրում։' },
  { id: 'wa-052', category: 'general', text: 'Անձրևին ի՞նչ ես բացում գլխիդ վրա։' },
  { id: 'wa-053', category: 'general', text: 'Ինչո՞վ ես հատակն ավլում։' },
  { id: 'wa-054', category: 'general', text: 'Քնելիս գլխիդ տակ ի՞նչ ես դնում։' },
  { id: 'wa-055', category: 'general', text: 'Քնելիս ինչո՞վ ես ծածկվում։' },
  { id: 'wa-056', category: 'general', text: 'Փողդ ինչի՞ մեջ ես պահում։' },
  { id: 'wa-057', category: 'general', text: 'Գրքերդ դպրոց ինչո՞վ ես տանում։' },
  { id: 'wa-058', category: 'general', text: 'Ինչո՞վ ես շորերն արդուկում։' },
  { id: 'wa-059', category: 'general', text: 'Ուտելիքն ինչի՞ մեջ ես դնում սեղանին։' },
  { id: 'wa-060', category: 'general', text: 'Ի՞նչ ես դնում աչքերիդ, որ լավ տեսնես։' },
  { id: 'wa-061', category: 'general', text: 'Ձմռանը վզիդ ի՞նչ ես փաթաթում։' },
  { id: 'wa-062', category: 'general', text: 'Աղբը ո՞ւր ես գցում։' },
  { id: 'wa-063', category: 'general', text: 'Ծննդյան տորթի վրա ի՞նչ ես փչում։' },
  { id: 'wa-064', category: 'general', text: 'Ուտելիս ինչի՞ շուրջ ես նստում։' },
  { id: 'wa-065', category: 'general', text: 'Ինչո՞վ ես մազերդ լվանում։' },
  { id: 'wa-066', category: 'general', text: 'Հիվանդանալիս ո՞ւմ մոտ ես գնում։' },
  { id: 'wa-067', category: 'general', text: 'Դպրոցում ո՞վ է դաս տալիս։' },
  { id: 'wa-068', category: 'general', text: 'Ո՞վ է հրդեհը հանգցնում։' },
  { id: 'wa-069', category: 'general', text: 'Դռան մոտ ի՞նչ ես սեղմում, որ բացեն։' },
  { id: 'wa-070', category: 'general', text: 'Վերքի վրա ի՞նչ ես կպցնում։' },
  { id: 'wa-071', category: 'general', text: 'Թեյն ինչի՞ մեջ ես լցնում։' },

  // Body, actions and senses.
  { id: 'wa-072', category: 'general', text: 'Ինչո՞վ ես լսում։' },
  { id: 'wa-073', category: 'general', text: 'Ինչո՞վ ես հոտ առնում։' },
  { id: 'wa-074', category: 'general', text: 'Ինչո՞վ ես համը զգում։' },
  { id: 'wa-075', category: 'general', text: 'Գլխիդ վրա ի՞նչ է աճում։' },
  { id: 'wa-076', category: 'general', text: 'Կրծքիդ մեջ ի՞նչ է բաբախում։' },
  { id: 'wa-077', category: 'general', text: 'Ի՞նչ ես շնչում։' },
  { id: 'wa-078', category: 'general', text: 'Ի՞նչ ես անում, երբ հոգնած ես։' },
  { id: 'wa-079', category: 'general', text: 'Ի՞նչ ես անում, երբ սոված ես։' },
  { id: 'wa-080', category: 'general', text: 'Լացելիս աչքերիցդ ի՞նչ է հոսում։' },
  { id: 'wa-081', category: 'general', text: 'Քնելիս ի՞նչ ես փակում։' },
  { id: 'wa-082', category: 'general', text: 'Մատանին որտե՞ղ ես դնում։' },
  { id: 'wa-083', category: 'general', text: 'Ժամացույցը որտե՞ղ ես կապում։' },
  { id: 'wa-084', category: 'general', text: 'Ի՞նչ ես անում, երբ ծիծաղելի բան ես լսում։' },
  { id: 'wa-085', category: 'general', text: 'Ի՞նչ ես ասում, երբ մեկը փռշտում է։' },
  { id: 'wa-086', category: 'general', text: 'Ֆուտբոլում գնդակին ինչո՞վ են խփում։' },
  { id: 'wa-087', category: 'general', text: 'Մատներիդ ծայրին ի՞նչ կա։' },
  { id: 'wa-088', category: 'general', text: 'Ի՞նչ գույնի է արյունը։' },
  { id: 'wa-089', category: 'general', text: 'Ձեռքդ որտեղի՞ց է ծալվում։' },

  // Animals and nature.
  { id: 'wa-090', category: 'general', text: 'Ո՞ր կենդանին ունի երկար վիզ։' },
  { id: 'wa-091', category: 'general', text: 'Ո՞վ է կենդանիների արքան։' },
  { id: 'wa-092', category: 'general', text: 'Ո՞ր կենդանին է կռկռում։' },
  { id: 'wa-093', category: 'general', text: 'Ո՞ր կենդանին է սիրում բանան։' },
  { id: 'wa-094', category: 'general', text: 'Ո՞ր կենդանուց ենք բուրդ ստանում։' },
  { id: 'wa-095', category: 'general', text: 'Ո՞վ է սարդոստայն հյուսում։' },
  { id: 'wa-096', category: 'general', text: 'Ի՞նչ գույնի է ագռավը։' },
  { id: 'wa-097', category: 'general', text: 'Կատուն ի՞նչ է բռնում։' },
  { id: 'wa-098', category: 'general', text: 'Ո՞ր եղանակին են տերևները թափվում։' },
  { id: 'wa-099', category: 'general', text: 'Ո՞ր կենդանին է կուկուրիկու անում։' },
  { id: 'wa-100', category: 'general', text: 'Ո՞ր կենդանին ունի կուզ։' },
  { id: 'wa-101', category: 'general', text: 'Անձրևից հետո երկնքում ի՞նչ է երևում։' },
  { id: 'wa-102', category: 'general', text: 'Կայծակից հետո ի՞նչ ես լսում։' },

  // Food and drinks.
  { id: 'wa-103', category: 'food', text: 'Ծննդյան օրդ ի՞նչ ես կտրում։' },
  { id: 'wa-104', category: 'food', text: 'Հացն ինչի՞ց են թխում։' },
  { id: 'wa-105', category: 'food', text: 'Ձվի դեղին մասն ի՞նչ է կոչվում։' },
  { id: 'wa-106', category: 'food', text: 'Ի՞նչ համ ունի կիտրոնը։' },
  { id: 'wa-107', category: 'food', text: 'Ի՞նչ ես գցում կերակրի մեջ, որ աղի լինի։' },
  { id: 'wa-108', category: 'food', text: 'Պանիրն ինչի՞ց են սարքում։' },
  { id: 'wa-109', category: 'food', text: 'Ո՞ր բանջարեղենն է կտրելիս լացացնում։' },
  { id: 'wa-110', category: 'food', text: 'Նապաստակն ի՞նչ է սիրում ուտել։' },
  { id: 'wa-111', category: 'food', text: 'Ֆրին ինչի՞ց են սարքում։' },
  { id: 'wa-112', category: 'food', text: 'Ո՞ր միրգն է լիքը կարմիր հատիկներով։' },
  { id: 'wa-113', category: 'food', text: 'Պոպկորնն ինչի՞ց են սարքում։' },
  { id: 'wa-114', category: 'funny', text: 'Պաղպաղակը տա՞ք է, թե՞ սառը։' },
  { id: 'wa-115', category: 'food', text: 'Արևի տակ պաղպաղակն ի՞նչ է լինում։' },
  { id: 'wa-116', category: 'food', text: 'Ինչո՞վ ես մակարոն ուտում։' },
  { id: 'wa-117', category: 'food', text: 'Ձմերուկի մեջ ամենաշատն ի՞նչ կա։' },
  { id: 'wa-118', category: 'food', text: 'Ձվածեղն ինչի՞ց են սարքում։' },
  { id: 'wa-119', category: 'food', text: 'Ի՞նչ համ ունի շաքարը։' },
  { id: 'wa-120', category: 'food', text: 'Խաղողը չորացնելիս ի՞նչ է դառնում։' },
  { id: 'wa-121', category: 'food', text: 'Կարագն ինչի՞ վրա ես քսում։' },

  // Numbers, time and basic concepts.
  { id: 'wa-122', category: 'general', text: 'Տարին քանի՞ ամիս ունի։' },
  { id: 'wa-123', category: 'general', text: 'Օրը քանի՞ ժամ ունի։' },
  { id: 'wa-124', category: 'general', text: 'Երկուշաբթիից հետո ո՞ր օրն է։' },
  { id: 'wa-125', category: 'general', text: 'Տարվա վերջին ամիսն ո՞րն է։' },
  { id: 'wa-126', category: 'general', text: 'Իննից հետո ո՞ր թիվն է։' },
  { id: 'wa-127', category: 'general', text: 'Տասի կեսը քանի՞ է։' },
  { id: 'wa-128', category: 'general', text: 'Ի՞նչն է մեծի հակառակը։' },
  { id: 'wa-129', category: 'general', text: 'Ի՞նչն է ցերեկվա հակառակը։' },
  { id: 'wa-130', category: 'general', text: 'Ի՞նչն է վերևի հակառակը։' },
  { id: 'wa-131', category: 'funny', text: 'Ո՞րն է մեծ՝ հինգը, թե՞ երեքը։' },
  { id: 'wa-132', category: 'general', text: 'Ո՞ր եղանակն է ամենաշոգը։' },
  { id: 'wa-133', category: 'general', text: 'Եռանկյունը քանի՞ կողմ ունի։' },
  { id: 'wa-134', category: 'general', text: 'Ի՞նչ ձև ունի գնդակը։' },

  // Simple geography and world knowledge.
  { id: 'wa-135', category: 'general', text: 'Ո՞ր մոլորակի վրա ենք ապրում։' },
  { id: 'wa-136', category: 'general', text: 'Ցերեկը երկնքում ի՞նչ է լույս տալիս։' },
  { id: 'wa-137', category: 'general', text: 'Ինչո՞վ ես մեխը խփում։' },
  { id: 'wa-138', category: 'general', text: 'Քանի՞ աչք ունես։' },
  { id: 'wa-139', category: 'general', text: 'Ո՞ր կենդանին է մեղր սիրում։' },
  { id: 'wa-140', category: 'general', text: 'Ի՞նչ ես բացում, որ սենյակը օդ մտնի։' },
  { id: 'wa-141', category: 'general', text: 'Ի՞նչ ես փչում, որ ուռչի։' },
  { id: 'wa-142', category: 'general', text: 'Պատուհանին ի՞նչ ես կախում։' },
  { id: 'wa-143', category: 'food', text: 'Կծու պղպեղը բերանդ ի՞նչ է անում։' },
  { id: 'wa-144', category: 'funny', text: 'Հյուսիսային բևեռում ցու՞րտ է, թե՞ շոգ։' },
  { id: 'wa-145', category: 'general', text: 'Ծովի ջուրն աղի՞ է, թե՞ քաղցր։' },
  { id: 'wa-146', category: 'general', text: 'Ինչո՞վ ես ծամում։' },
  { id: 'wa-147', category: 'general', text: 'Վարորդն ինչո՞վ է մեքենան շրջում։' },
  { id: 'wa-148', category: 'general', text: 'Մոտոցիկլ քշելիս գլխիդ ի՞նչ ես դնում։' },
  { id: 'wa-149', category: 'general', text: 'Մատիտով գրածն ինչո՞վ ես ջնջում։' },
  { id: 'wa-150', category: 'funny', text: 'Ո՞րն է մեծ՝ քաղաքը, թե՞ գյուղը։' },
  { id: 'wa-151', category: 'general', text: 'Անգլիայում ի՞նչ լեզվով են խոսում։' },
  { id: 'wa-152', category: 'food', text: 'Գինին ինչի՞ց են սարքում։' },
  { id: 'wa-153', category: 'general', text: 'Խոհանոցում ջուրն որտեղի՞ց է հոսում։' },

  // Armenia — things every Armenian at the table knows without thinking.
  { id: 'wa-154', category: 'armenia', text: 'Ամանորին Հայաստանում ո՞վ է նվերներ բերում։' },
  { id: 'wa-155', category: 'armenia', text: 'Հայաստանի ամենամեծ լիճն ո՞րն է։' },
  { id: 'wa-156', category: 'armenia', text: 'Հայաստանում ձմռանը ձյուն գալի՞ս է։' },
  { id: 'wa-157', category: 'armenia', text: 'Հայոց այբուբենի առաջին տառն ո՞րն է։' },
  { id: 'wa-158', category: 'armenia', text: 'Թոնրում ի՞նչ հաց են թխում։' },
  { id: 'wa-159', category: 'armenia', text: 'Դուդուկը նվագարա՞ն է, թե՞ ուտելիք։' },
  { id: 'wa-160', category: 'yerevan', text: 'Երևանում ապրողներին ինչպե՞ս են ասում։' },
  { id: 'wa-161', category: 'armenia', text: 'Հայաստանի դրոշը քանի՞ գույն ունի։' },
  { id: 'wa-162', category: 'armenia', text: 'Խաշը ո՞ր եղանակին են ուտում։' },
  { id: 'wa-163', category: 'armenia', text: 'Հայաստանի փողն ի՞նչ է կոչվում։' },
  { id: 'wa-164', category: 'general', text: 'Ո՞ր կենդանին ունի երկար ականջներ ու ցատկում է։' },
  { id: 'wa-165', category: 'armenia', text: 'Շամփուրով եփած միսն ի՞նչ է կոչվում։' },
  { id: 'wa-166', category: 'general', text: 'Ի՞նչ ես ասում, երբ մեկի ծնունդն է։' },
  { id: 'wa-167', category: 'armenia', text: 'Խաղողի տերևով ի՞նչ են փաթաթում։' },
  { id: 'wa-168', category: 'armenia', text: 'Լավաշը բարա՞կ է, թե՞ հաստ։' },
  { id: 'wa-169', category: 'armenia', text: 'Վարդավառին իրար վրա ի՞նչ են լցնում։' },
  { id: 'wa-170', category: 'funny', text: 'Հայաստանը ծով ունի՞։' },
  { id: 'wa-171', category: 'general', text: 'Լողավազանում ի՞նչ ես անում։' },
  { id: 'wa-172', category: 'armenia', text: 'Զատիկին ի՞նչ են ներկում։' },
  { id: 'wa-173', category: 'armenia', text: 'Հայաստանի սարն ո՞րն է։' },
  { id: 'wa-174', category: 'general', text: 'Պատին ի՞նչ ես կախում, որ ժամն իմանաս։' },
  { id: 'wa-175', category: 'general', text: 'Ինչո՞վ ես ծափ տալիս։' },
  { id: 'wa-176', category: 'yerevan', text: 'Երևանն ի՞նչ գույնի քաղաք է։' },
  { id: 'wa-177', category: 'general', text: 'Կոշիկներդ ինչո՞վ ես կապում։' },

  // Technology, household and transport.
  { id: 'wa-178', category: 'general', text: 'Ինչո՞վ են երկնքով ճանապարհորդում։' },
  { id: 'wa-179', category: 'general', text: 'Ի՞նչն է ընթանում ռելսերով։' },
  { id: 'wa-180', category: 'general', text: 'Ի՞նչն ունի երկու անիվ ու ոտնակներ։' },
  { id: 'wa-181', category: 'general', text: 'Լուսացույցի ո՞ր գույնի վրա ես կանգնում։' },
  { id: 'wa-182', category: 'general', text: 'Ինչի՞ մեջ ես ուտելիքն արագ տաքացնում։' },
  { id: 'wa-183', category: 'general', text: 'Ինչի՞ մեջ ես շորերը լցնում լվանալու։' },
  { id: 'wa-184', category: 'general', text: 'Ականջներիդ ի՞նչ ես դնում երաժշտություն լսելու։' },
  { id: 'wa-185', category: 'general', text: 'Ինչո՞վ ես հեռուստացույցի ալիքը փոխում։' },
  { id: 'wa-186', category: 'general', text: 'Բարձր շենքում ինչո՞վ ես վերև բարձրանում։' },
  { id: 'wa-187', category: 'general', text: 'Հիվանդին հիվանդանոց ո՞ր մեքենան է տանում։' },
  { id: 'wa-188', category: 'general', text: 'Ինքնաթիռները որտե՞ղ են իջնում։' },

  // Trick-style prompts — the answer is in the room.
  { id: 'wa-189', category: 'funny', text: 'Ի՞նչ լեզվով ես հիմա խոսում։' },
  { id: 'wa-190', category: 'funny', text: 'Քանի՞ քիթ ունես։' },
  { id: 'wa-191', category: 'funny', text: 'Քո անունն ի՞նչ է։' },
  { id: 'wa-192', category: 'funny', text: 'Կրակը տա՞ք է, թե՞ սառը։' },
  { id: 'wa-193', category: 'funny', text: 'Ձուկը ոտքեր ունի՞։' },
  { id: 'wa-194', category: 'funny', text: 'Խոզերը թռչո՞ւմ են։' },
  { id: 'wa-195', category: 'funny', text: 'Հեռախոսը վերցնելիս ի՞նչ ես ասում։' },
  { id: 'wa-196', category: 'funny', text: 'Ի՞նչն է «այո»-ի հակառակը։' },
  { id: 'wa-197', category: 'funny', text: 'Ո՞րն է ավելի բարձր՝ շշուկը, թե՞ ճիչը։' },
  { id: 'wa-198', category: 'funny', text: 'Ո՞րն է ավելի մեծ՝ փիղը, թե՞ մուկը։' },
  { id: 'wa-199', category: 'funny', text: 'Կարմիր խնձորն ի՞նչ գույնի է։' },
  { id: 'wa-200', category: 'funny', text: 'Ո՞րն է ավելի արագ՝ մեքենան, թե՞ հեծանիվը։' },
];
