import type { Prompt } from './types';

/**
 * Same Answer deck — 200 prompts.
 * Rules for every prompt: a handful of obvious answers (not one, not hundreds), no special
 * knowledge, nothing political or personal, nothing a table would argue about.
 * Ids are shared with `hy.ts`; add a prompt to both files or to neither. The two decks are not
 * translations: Armenian is Armenia-first, English must work for players with no Armenian
 * background, so the same id can carry a completely different prompt.
 */
export const sameAnswerEn: Prompt[] = [
  { id: 'sa-001', category: 'food', text: 'Name a food you eat with your hands.' },
  { id: 'sa-002', category: 'food', text: 'Name a fruit.' },
  { id: 'sa-003', category: 'food', text: 'Name a vegetable.' },
  { id: 'sa-004', category: 'food', text: 'Name something people eat for breakfast.' },
  { id: 'sa-005', category: 'food', text: 'Name a pizza topping.' },
  { id: 'sa-006', category: 'food', text: 'Name a hot drink.' },
  { id: 'sa-007', category: 'food', text: 'Name a dessert.' },
  { id: 'sa-008', category: 'food', text: 'Name a dairy product.' },
  { id: 'sa-009', category: 'food', text: 'Name a fast food.' },
  { id: 'sa-010', category: 'food', text: 'Name a fresh herb you put in salad.' },
  { id: 'sa-011', category: 'food', text: 'Name something you spread on bread.' },
  { id: 'sa-012', category: 'food', text: 'Name something people put in tea.' },
  { id: 'sa-013', category: 'food', text: 'Name an ice cream flavor.' },
  { id: 'sa-014', category: 'food', text: 'Name a type of cake.' },
  { id: 'sa-015', category: 'food', text: 'Name a soup.' },
  { id: 'sa-016', category: 'food', text: 'Name a summer fruit.' },
  { id: 'sa-017', category: 'food', text: 'Name a juice.' },
  { id: 'sa-018', category: 'food', text: 'Name something you grill.' },
  { id: 'sa-019', category: 'places', text: 'Name a famous city.' },
  { id: 'sa-020', category: 'entertainment', text: 'Name a famous singer.' },
  { id: 'sa-021', category: 'social', text: 'Name something people do before bed.' },
  { id: 'sa-022', category: 'travel', text: 'Name a country people visit on vacation.' },
  { id: 'sa-023', category: 'social', text: 'Name a holiday.' },
  { id: 'sa-024', category: 'everyday', text: 'Name a flower.' },
  { id: 'sa-025', category: 'entertainment', text: 'Name a toy.' },
  { id: 'sa-026', category: 'entertainment', text: 'Name a dance.' },
  { id: 'sa-027', category: 'food', text: 'Name something you buy at a bakery.' },
  { id: 'sa-028', category: 'objects', text: 'Name something found in an office.' },
  { id: 'sa-029', category: 'everyday', text: 'Name a clothing brand.' },
  { id: 'sa-030', category: 'social', text: 'Name something people are afraid of.' },
  { id: 'sa-031', category: 'places', text: 'Name a famous landmark.' },
  { id: 'sa-032', category: 'everyday', text: 'Name a household chore.' },
  { id: 'sa-033', category: 'animals', text: 'Name an animal people keep at home.' },
  { id: 'sa-034', category: 'animals', text: 'Name a farm animal.' },
  { id: 'sa-035', category: 'animals', text: 'Name a wild animal.' },
  { id: 'sa-036', category: 'animals', text: 'Name a bird.' },
  { id: 'sa-037', category: 'animals', text: 'Name an animal that lives in the sea.' },
  { id: 'sa-038', category: 'animals', text: 'Name an insect.' },
  { id: 'sa-039', category: 'animals', text: 'Name an animal with stripes.' },
  { id: 'sa-040', category: 'animals', text: 'Name a zoo animal.' },
  { id: 'sa-041', category: 'everyday', text: 'Name something that smells good.' },
  { id: 'sa-042', category: 'animals', text: 'Name an animal from a fairy tale.' },
  { id: 'sa-043', category: 'everyday', text: 'Name something red.' },
  { id: 'sa-044', category: 'everyday', text: 'Name something yellow.' },
  { id: 'sa-045', category: 'everyday', text: 'Name something green.' },
  { id: 'sa-046', category: 'everyday', text: 'Name something white.' },
  { id: 'sa-047', category: 'everyday', text: 'Name something cold.' },
  { id: 'sa-048', category: 'everyday', text: 'Name something hot.' },
  { id: 'sa-049', category: 'everyday', text: 'Name something sweet.' },
  { id: 'sa-050', category: 'everyday', text: 'Name something round.' },
  { id: 'sa-051', category: 'objects', text: 'Name something found in a kitchen.' },
  { id: 'sa-052', category: 'objects', text: 'Name something found in a bathroom.' },
  { id: 'sa-053', category: 'objects', text: 'Name something in a school bag.' },
  { id: 'sa-054', category: 'objects', text: 'Name something you wear on your feet.' },
  { id: 'sa-055', category: 'objects', text: 'Name something you wear in winter.' },
  { id: 'sa-056', category: 'objects', text: 'Name something you take to the beach.' },
  { id: 'sa-057', category: 'objects', text: 'Name a piece of furniture.' },
  { id: 'sa-058', category: 'objects', text: 'Name something in a wallet.' },
  { id: 'sa-059', category: 'objects', text: 'Name something people keep in a pocket.' },
  { id: 'sa-060', category: 'objects', text: 'Name something in a fridge.' },
  { id: 'sa-061', category: 'objects', text: 'Name a part of a car.' },
  { id: 'sa-062', category: 'objects', text: 'Name a tool.' },
  { id: 'sa-063', category: 'technology', text: 'Name something that runs on batteries.' },
  { id: 'sa-064', category: 'everyday', text: 'Name something you use every morning.' },
  { id: 'sa-065', category: 'everyday', text: 'Name a body part.' },
  { id: 'sa-066', category: 'everyday', text: 'Name a shape.' },
  { id: 'sa-067', category: 'everyday', text: 'Name a school subject.' },
  { id: 'sa-068', category: 'everyday', text: 'Name a job.' },
  { id: 'sa-069', category: 'objects', text: 'Name something with wheels.' },
  { id: 'sa-070', category: 'objects', text: 'Name something you buy at a pharmacy.' },
  { id: 'sa-071', category: 'places', text: 'Name a country in Europe.' },
  { id: 'sa-072', category: 'social', text: 'Name something people take on a picnic.' },
  { id: 'sa-073', category: 'places', text: 'Name a place people go on a first date.' },
  { id: 'sa-074', category: 'travel', text: 'Name something you pack in a suitcase.' },
  { id: 'sa-075', category: 'travel', text: 'Name a kind of transport.' },
  { id: 'sa-076', category: 'travel', text: 'Name something found at an airport.' },
  { id: 'sa-077', category: 'travel', text: 'Name something people do on vacation.' },
  { id: 'sa-078', category: 'places', text: 'Name a language.' },
  { id: 'sa-079', category: 'places', text: 'Name a continent.' },
  { id: 'sa-080', category: 'places', text: 'Name a place that is always crowded.' },
  { id: 'sa-081', category: 'places', text: 'Name something you see in a park.' },
  { id: 'sa-082', category: 'technology', text: 'Name a social media app.' },
  { id: 'sa-083', category: 'entertainment', text: 'Name a sport.' },
  { id: 'sa-084', category: 'entertainment', text: 'Name a board game.' },
  { id: 'sa-085', category: 'entertainment', text: 'Name a superhero.' },
  { id: 'sa-086', category: 'entertainment', text: 'Name a cartoon character.' },
  { id: 'sa-087', category: 'entertainment', text: 'Name a musical instrument.' },
  { id: 'sa-088', category: 'food', text: 'Name a snack people eat at a party.' },
  { id: 'sa-089', category: 'technology', text: 'Name a phone brand.' },
  { id: 'sa-090', category: 'technology', text: 'Name a car brand.' },
  { id: 'sa-091', category: 'everyday', text: 'Name a color people wear often.' },
  { id: 'sa-092', category: 'entertainment', text: 'Name a movie everyone has seen.' },
  { id: 'sa-093', category: 'technology', text: 'Name a messaging app.' },
  { id: 'sa-094', category: 'entertainment', text: 'Name a music genre.' },
  { id: 'sa-095', category: 'social', text: 'Name something people do when they can’t sleep.' },
  { id: 'sa-096', category: 'entertainment', text: 'Name a children’s game.' },
  { id: 'sa-097', category: 'social', text: 'Name an excuse for being late.' },
  { id: 'sa-098', category: 'social', text: 'Name a reason to celebrate.' },
  { id: 'sa-099', category: 'social', text: 'Name something people do at a wedding.' },
  { id: 'sa-100', category: 'social', text: 'Name a birthday present.' },

  // Second hundred — senses, materials, places and habits.
  { id: 'sa-101', category: 'food', text: 'Name a cold drink.' },
  { id: 'sa-102', category: 'food', text: 'Name something salty.' },
  { id: 'sa-103', category: 'food', text: 'Name something sour.' },
  { id: 'sa-104', category: 'food', text: 'Name something spicy.' },
  { id: 'sa-105', category: 'food', text: 'Name something you fry.' },
  { id: 'sa-106', category: 'food', text: 'Name something you buy at a market.' },
  { id: 'sa-107', category: 'food', text: 'Name a kind of nut.' },
  { id: 'sa-108', category: 'food', text: 'Name a dish made with rice.' },
  { id: 'sa-109', category: 'food', text: 'Name something made from fruit.' },
  { id: 'sa-110', category: 'food', text: 'Name something people eat at the cinema.' },
  { id: 'sa-111', category: 'food', text: 'Name a dish made with eggs.' },
  { id: 'sa-112', category: 'food', text: 'Name something made from milk.' },
  { id: 'sa-113', category: 'food', text: 'Name something made from dough.' },
  { id: 'sa-114', category: 'food', text: 'Name something you put in a salad.' },
  { id: 'sa-115', category: 'food', text: 'Name something you put in a burger.' },
  { id: 'sa-116', category: 'armenia', text: 'Name a common first name.' },
  { id: 'sa-117', category: 'armenia', text: 'Name a famous writer.' },
  { id: 'sa-118', category: 'armenia', text: 'Name a famous mountain.' },
  { id: 'sa-119', category: 'armenia', text: 'Name a famous river.' },
  { id: 'sa-120', category: 'armenia', text: 'Name a famous street.' },
  { id: 'sa-121', category: 'armenia', text: 'Name a state in the USA.' },
  { id: 'sa-122', category: 'armenia', text: 'Name a type of cheese.' },
  { id: 'sa-123', category: 'armenia', text: 'Name a famous actor.' },
  { id: 'sa-124', category: 'armenia', text: 'Name a Disney movie.' },
  { id: 'sa-125', category: 'armenia', text: 'Name a brand of bottled water.' },
  { id: 'sa-126', category: 'animals', text: 'Name an animal that sleeps all winter.' },
  { id: 'sa-127', category: 'animals', text: 'Name an animal that lives in a tree.' },
  { id: 'sa-128', category: 'animals', text: 'Name an animal that runs fast.' },
  { id: 'sa-129', category: 'animals', text: 'Name a slow animal.' },
  { id: 'sa-130', category: 'animals', text: 'Name an animal that gives milk.' },
  { id: 'sa-131', category: 'animals', text: 'Name an animal that lays eggs.' },
  { id: 'sa-132', category: 'animals', text: 'Name an animal that swims.' },
  { id: 'sa-133', category: 'animals', text: 'Name an animal that is awake at night.' },
  { id: 'sa-134', category: 'animals', text: 'Name an animal that jumps.' },
  { id: 'sa-135', category: 'animals', text: 'Name an animal with horns.' },
  { id: 'sa-136', category: 'everyday', text: 'Name something black.' },
  { id: 'sa-137', category: 'everyday', text: 'Name something blue.' },
  { id: 'sa-138', category: 'everyday', text: 'Name something soft.' },
  { id: 'sa-139', category: 'everyday', text: 'Name something heavy.' },
  { id: 'sa-140', category: 'everyday', text: 'Name something that shines.' },
  { id: 'sa-141', category: 'everyday', text: 'Name something fast.' },
  { id: 'sa-142', category: 'everyday', text: 'Name something loud.' },
  { id: 'sa-143', category: 'everyday', text: 'Name something you see in the sky.' },
  { id: 'sa-144', category: 'everyday', text: 'Name something people do every evening.' },
  { id: 'sa-145', category: 'everyday', text: 'Name something people do on the weekend.' },
  { id: 'sa-146', category: 'everyday', text: 'Name something people forget at home.' },
  { id: 'sa-147', category: 'everyday', text: 'Name something people buy every day.' },
  { id: 'sa-148', category: 'everyday', text: 'Name something moms always say.' },
  { id: 'sa-149', category: 'everyday', text: 'Name something people do in summer.' },
  { id: 'sa-150', category: 'everyday', text: 'Name something people do in winter.' },
  { id: 'sa-151', category: 'everyday', text: 'Name something people do at the gym.' },
  { id: 'sa-152', category: 'everyday', text: 'Name something very expensive.' },
  { id: 'sa-153', category: 'everyday', text: 'Name something that is free.' },
  { id: 'sa-154', category: 'everyday', text: 'Name something there is never enough of.' },
  { id: 'sa-155', category: 'everyday', text: 'Name something kids do not like.' },
  { id: 'sa-156', category: 'objects', text: 'Name something found in a bedroom.' },
  { id: 'sa-157', category: 'objects', text: 'Name something you hang on a wall.' },
  { id: 'sa-158', category: 'objects', text: 'Name something you open with a key.' },
  { id: 'sa-159', category: 'objects', text: 'Name something made of glass.' },
  { id: 'sa-160', category: 'objects', text: 'Name something made of wood.' },
  { id: 'sa-161', category: 'objects', text: 'Name something made of metal.' },
  { id: 'sa-162', category: 'objects', text: 'Name something you wear on your head.' },
  { id: 'sa-163', category: 'objects', text: 'Name something you wear on your wrist.' },
  { id: 'sa-164', category: 'objects', text: 'Name something people keep in a car.' },
  { id: 'sa-165', category: 'objects', text: 'Name something found in a kid’s room.' },
  { id: 'sa-166', category: 'objects', text: 'Name something that plugs into a wall.' },
  { id: 'sa-167', category: 'objects', text: 'Name something you cut with scissors.' },
  { id: 'sa-168', category: 'objects', text: 'Name something you wash.' },
  { id: 'sa-169', category: 'objects', text: 'Name something sold in a bottle.' },
  { id: 'sa-170', category: 'technology', text: 'Name something with a screen.' },
  { id: 'sa-171', category: 'technology', text: 'Name something that needs the internet.' },
  { id: 'sa-172', category: 'technology', text: 'Name something you charge.' },
  { id: 'sa-173', category: 'technology', text: 'Name a famous website.' },
  { id: 'sa-174', category: 'technology', text: 'Name something people do on their phone.' },
  { id: 'sa-175', category: 'technology', text: 'Name a part of a computer.' },
  { id: 'sa-176', category: 'places', text: 'Name a place where people wait in line.' },
  { id: 'sa-177', category: 'places', text: 'Name a place where you have to be quiet.' },
  { id: 'sa-178', category: 'places', text: 'Name a place kids love to go.' },
  { id: 'sa-179', category: 'places', text: 'Name a place that sells food.' },
  { id: 'sa-180', category: 'places', text: 'Name a country in Asia.' },
  { id: 'sa-181', category: 'places', text: 'Name a big country.' },
  { id: 'sa-182', category: 'places', text: 'Name a capital city.' },
  { id: 'sa-183', category: 'places', text: 'Name a place where you buy a ticket.' },
  { id: 'sa-184', category: 'places', text: 'Name a place where people study.' },
  { id: 'sa-185', category: 'places', text: 'Name a place where friends meet.' },
  { id: 'sa-186', category: 'entertainment', text: 'Name something people watch in the evening.' },
  { id: 'sa-187', category: 'entertainment', text: 'Name a famous TV series.' },
  { id: 'sa-188', category: 'entertainment', text: 'Name a game played with a ball.' },
  { id: 'sa-189', category: 'entertainment', text: 'Name a winter sport.' },
  { id: 'sa-190', category: 'entertainment', text: 'Name a famous football player.' },
  { id: 'sa-191', category: 'entertainment', text: 'Name something people do at a concert.' },
  { id: 'sa-192', category: 'entertainment', text: 'Name a fairy tale character.' },
  { id: 'sa-193', category: 'entertainment', text: 'Name something that is in every movie.' },
  { id: 'sa-194', category: 'entertainment', text: 'Name something people do to music.' },
  { id: 'sa-195', category: 'entertainment', text: 'Name something you win in a competition.' },
  { id: 'sa-196', category: 'social', text: 'Name a New Year’s resolution.' },
  { id: 'sa-197', category: 'social', text: 'Name something people say when leaving.' },
  { id: 'sa-198', category: 'social', text: 'Name something people apologize for.' },
  { id: 'sa-199', category: 'social', text: 'Name something that makes people happy.' },
  { id: 'sa-200', category: 'social', text: 'Name something that annoys people.' },
];
