import type { Prompt } from './types';

/**
 * Same Answer deck — 100 prompts.
 * Rules for every prompt: a handful of obvious answers (not one, not hundreds), no special
 * knowledge, nothing political or personal, nothing a table would argue about.
 * Ids are shared with `hy.ts`; add a prompt to both files or to neither.
 */
export const sameAnswerEn: Prompt[] = [
  { id: 'sa-001', category: 'food', text: 'Name an Armenian food.' },
  { id: 'sa-002', category: 'food', text: 'Name a fruit.' },
  { id: 'sa-003', category: 'food', text: 'Name a vegetable.' },
  { id: 'sa-004', category: 'food', text: 'Name something people eat for breakfast.' },
  { id: 'sa-005', category: 'food', text: 'Name a pizza topping.' },
  { id: 'sa-006', category: 'food', text: 'Name a hot drink.' },
  { id: 'sa-007', category: 'food', text: 'Name a dessert.' },
  { id: 'sa-008', category: 'food', text: 'Name a dairy product.' },
  { id: 'sa-009', category: 'food', text: 'Name a fast food.' },
  { id: 'sa-010', category: 'food', text: 'Name a fresh herb you put in salad.' },
  { id: 'sa-011', category: 'food', text: 'Name something you spread on bread.' },
  { id: 'sa-012', category: 'food', text: 'Name something people put in tea.' },
  { id: 'sa-013', category: 'food', text: 'Name an ice cream flavor.' },
  { id: 'sa-014', category: 'food', text: 'Name an Armenian sweet.' },
  { id: 'sa-015', category: 'food', text: 'Name a soup.' },
  { id: 'sa-016', category: 'food', text: 'Name a summer fruit.' },
  { id: 'sa-017', category: 'food', text: 'Name a juice.' },
  { id: 'sa-018', category: 'food', text: 'Name something you grill.' },
  { id: 'sa-019', category: 'armenia', text: 'Name an Armenian city.' },
  { id: 'sa-020', category: 'armenia', text: 'Name an Armenian singer.' },
  { id: 'sa-021', category: 'food', text: 'Name something on the New Year table.' },
  { id: 'sa-022', category: 'armenia', text: 'Name a place in Yerevan.' },
  { id: 'sa-023', category: 'armenia', text: 'Name an Armenian holiday.' },
  { id: 'sa-024', category: 'everyday', text: 'Name a flower.' },
  { id: 'sa-025', category: 'entertainment', text: 'Name a toy.' },
  { id: 'sa-026', category: 'armenia', text: 'Name an Armenian dance.' },
  { id: 'sa-027', category: 'food', text: 'Name something you buy at a bakery.' },
  { id: 'sa-028', category: 'objects', text: 'Name something found in an office.' },
  { id: 'sa-029', category: 'armenia', text: 'Name an Armenian brand.' },
  { id: 'sa-030', category: 'social', text: 'Name something people are afraid of.' },
  { id: 'sa-031', category: 'armenia', text: 'Name an Armenian monastery.' },
  { id: 'sa-032', category: 'everyday', text: 'Name a household chore.' },
  { id: 'sa-033', category: 'animals', text: 'Name an animal people keep at home.' },
  { id: 'sa-034', category: 'animals', text: 'Name an animal people keep in a village.' },
  { id: 'sa-035', category: 'animals', text: 'Name a wild animal.' },
  { id: 'sa-036', category: 'animals', text: 'Name a bird.' },
  { id: 'sa-037', category: 'animals', text: 'Name an animal that lives in the sea.' },
  { id: 'sa-038', category: 'animals', text: 'Name an insect.' },
  { id: 'sa-039', category: 'animals', text: 'Name an animal with stripes.' },
  { id: 'sa-040', category: 'animals', text: 'Name a zoo animal.' },
  { id: 'sa-041', category: 'everyday', text: 'Name something that smells good.' },
  { id: 'sa-042', category: 'animals', text: 'Name an animal from a fairy tale.' },
  { id: 'sa-043', category: 'everyday', text: 'Name something red.' },
  { id: 'sa-044', category: 'everyday', text: 'Name something yellow.' },
  { id: 'sa-045', category: 'everyday', text: 'Name something green.' },
  { id: 'sa-046', category: 'everyday', text: 'Name something white.' },
  { id: 'sa-047', category: 'everyday', text: 'Name something cold.' },
  { id: 'sa-048', category: 'everyday', text: 'Name something hot.' },
  { id: 'sa-049', category: 'everyday', text: 'Name something sweet.' },
  { id: 'sa-050', category: 'everyday', text: 'Name something round.' },
  { id: 'sa-051', category: 'objects', text: 'Name something found in a kitchen.' },
  { id: 'sa-052', category: 'objects', text: 'Name something found in a bathroom.' },
  { id: 'sa-053', category: 'objects', text: 'Name something in a school bag.' },
  { id: 'sa-054', category: 'objects', text: 'Name something you wear on your feet.' },
  { id: 'sa-055', category: 'objects', text: 'Name something you wear in winter.' },
  { id: 'sa-056', category: 'objects', text: 'Name something you take to the beach.' },
  { id: 'sa-057', category: 'objects', text: 'Name a piece of furniture.' },
  { id: 'sa-058', category: 'objects', text: 'Name something in a wallet.' },
  { id: 'sa-059', category: 'objects', text: 'Name something people keep in a pocket.' },
  { id: 'sa-060', category: 'objects', text: 'Name something in a fridge.' },
  { id: 'sa-061', category: 'objects', text: 'Name a part of a car.' },
  { id: 'sa-062', category: 'objects', text: 'Name a tool.' },
  { id: 'sa-063', category: 'technology', text: 'Name something that runs on batteries.' },
  { id: 'sa-064', category: 'everyday', text: 'Name something you use every morning.' },
  { id: 'sa-065', category: 'everyday', text: 'Name a body part.' },
  { id: 'sa-066', category: 'everyday', text: 'Name a shape.' },
  { id: 'sa-067', category: 'everyday', text: 'Name a school subject.' },
  { id: 'sa-068', category: 'everyday', text: 'Name a job.' },
  { id: 'sa-069', category: 'objects', text: 'Name something with wheels.' },
  { id: 'sa-070', category: 'objects', text: 'Name something you buy at a pharmacy.' },
  { id: 'sa-071', category: 'places', text: 'Name a country in Europe.' },
  { id: 'sa-072', category: 'social', text: 'Name something people take on a picnic.' },
  { id: 'sa-073', category: 'places', text: 'Name a place people go on a first date.' },
  { id: 'sa-074', category: 'travel', text: 'Name something you pack in a suitcase.' },
  { id: 'sa-075', category: 'travel', text: 'Name a kind of transport.' },
  { id: 'sa-076', category: 'travel', text: 'Name something found at an airport.' },
  { id: 'sa-077', category: 'travel', text: 'Name a place in Armenia people go to relax.' },
  { id: 'sa-078', category: 'places', text: 'Name a language.' },
  { id: 'sa-079', category: 'places', text: 'Name a continent.' },
  { id: 'sa-080', category: 'places', text: 'Name a place that is always crowded.' },
  { id: 'sa-081', category: 'places', text: 'Name something you see in a park.' },
  { id: 'sa-082', category: 'technology', text: 'Name a social media app.' },
  { id: 'sa-083', category: 'entertainment', text: 'Name a sport.' },
  { id: 'sa-084', category: 'entertainment', text: 'Name a board game.' },
  { id: 'sa-085', category: 'entertainment', text: 'Name a superhero.' },
  { id: 'sa-086', category: 'entertainment', text: 'Name a cartoon character.' },
  { id: 'sa-087', category: 'entertainment', text: 'Name a musical instrument.' },
  { id: 'sa-088', category: 'food', text: 'Name a snack people eat at a party.' },
  { id: 'sa-089', category: 'technology', text: 'Name a phone brand.' },
  { id: 'sa-090', category: 'technology', text: 'Name a car brand.' },
  { id: 'sa-091', category: 'everyday', text: 'Name a color people wear often.' },
  { id: 'sa-092', category: 'entertainment', text: 'Name a movie everyone has seen.' },
  { id: 'sa-093', category: 'technology', text: 'Name a messaging app.' },
  { id: 'sa-094', category: 'entertainment', text: 'Name a music genre.' },
  { id: 'sa-095', category: 'social', text: 'Name something people do when they can’t sleep.' },
  { id: 'sa-096', category: 'entertainment', text: 'Name a children’s game.' },
  { id: 'sa-097', category: 'social', text: 'Name an excuse for being late.' },
  { id: 'sa-098', category: 'social', text: 'Name a reason to celebrate.' },
  { id: 'sa-099', category: 'social', text: 'Name something people do at a wedding.' },
  { id: 'sa-100', category: 'social', text: 'Name a birthday present.' },
];
