import type { Prompt } from './types';

/**
 * Same Answer deck — 200 prompts, paired 1:1 with the English ids.
 * Spoken Eastern Armenian, the way you would say it across a table: «Ասա մի…».
 * A handful of obvious answers each, nothing to argue about, nothing political.
 */
export const sameAnswerHy: Prompt[] = [
  { id: 'sa-001', category: 'food', text: 'Ասա մի հայկական ուտեստ։' },
  { id: 'sa-002', category: 'food', text: 'Ասա մի միրգ։' },
  { id: 'sa-003', category: 'food', text: 'Ասա մի բանջարեղեն։' },
  { id: 'sa-004', category: 'food', text: 'Ասա մի բան, որ նախաճաշին են ուտում։' },
  { id: 'sa-005', category: 'food', text: 'Ասա մի բան, որ պիցցայի վրա են դնում։' },
  { id: 'sa-006', category: 'food', text: 'Ասա մի տաք ըմպելիք։' },
  { id: 'sa-007', category: 'food', text: 'Ասա մի դեսերտ։' },
  { id: 'sa-008', category: 'food', text: 'Ասա մի կաթնամթերք։' },
  { id: 'sa-009', category: 'food', text: 'Ասա մի ֆաստ ֆուդ։' },
  { id: 'sa-010', category: 'food', text: 'Ասա մի կանաչի։' },
  { id: 'sa-011', category: 'food', text: 'Ասա մի բան, որ հացի վրա են քսում։' },
  { id: 'sa-012', category: 'food', text: 'Ասա մի բան, որ թեյի մեջ են դնում։' },
  { id: 'sa-013', category: 'food', text: 'Ասա պաղպաղակի մի համ։' },
  { id: 'sa-014', category: 'food', text: 'Ասա մի հայկական քաղցրավենիք։' },
  { id: 'sa-015', category: 'food', text: 'Ասա մի ապուր։' },
  { id: 'sa-016', category: 'food', text: 'Ասա մի ամառային միրգ։' },
  { id: 'sa-017', category: 'food', text: 'Ասա մի հյութ։' },
  { id: 'sa-018', category: 'food', text: 'Ասա մի բան, որ խորովում են։' },
  { id: 'sa-019', category: 'armenia', text: 'Ասա մի հայկական քաղաք։' },
  { id: 'sa-020', category: 'armenia', text: 'Ասա մի հայ երգիչ։' },
  { id: 'sa-021', category: 'food', text: 'Ասա մի բան, որ Ամանորի սեղանին է լինում։' },
  { id: 'sa-022', category: 'armenia', text: 'Ասա Երևանի մի վայր։' },
  { id: 'sa-023', category: 'armenia', text: 'Ասա մի հայկական տոն։' },
  { id: 'sa-024', category: 'everyday', text: 'Ասա մի ծաղիկ։' },
  { id: 'sa-025', category: 'entertainment', text: 'Ասա մի խաղալիք։' },
  { id: 'sa-026', category: 'armenia', text: 'Ասա մի հայկական պար։' },
  { id: 'sa-027', category: 'food', text: 'Ասա մի բան, որ փռից են գնում։' },
  { id: 'sa-028', category: 'objects', text: 'Ասա մի բան, որ գրասենյակում է լինում։' },
  { id: 'sa-029', category: 'armenia', text: 'Ասա մի հայկական բրենդ։' },
  { id: 'sa-030', category: 'social', text: 'Ասա մի բան, որից մարդիկ վախենում են։' },
  { id: 'sa-031', category: 'armenia', text: 'Ասա մի հայկական վանք։' },
  { id: 'sa-032', category: 'everyday', text: 'Ասա մի տնային գործ։' },
  { id: 'sa-033', category: 'animals', text: 'Ասա մի կենդանի, որ տանը պահում են։' },
  { id: 'sa-034', category: 'animals', text: 'Ասա մի կենդանի, որ գյուղում պահում են։' },
  { id: 'sa-035', category: 'animals', text: 'Ասա մի վայրի կենդանի։' },
  { id: 'sa-036', category: 'animals', text: 'Ասա մի թռչուն։' },
  { id: 'sa-037', category: 'animals', text: 'Ասա մի կենդանի, որ ծովում է ապրում։' },
  { id: 'sa-038', category: 'animals', text: 'Ասա մի միջատ։' },
  { id: 'sa-039', category: 'animals', text: 'Ասա մի գծավոր կենդանի։' },
  { id: 'sa-040', category: 'animals', text: 'Ասա կենդանաբանական այգու մի կենդանի։' },
  { id: 'sa-041', category: 'everyday', text: 'Ասա մի բան, որ լավ հոտ ունի։' },
  { id: 'sa-042', category: 'animals', text: 'Ասա հեքիաթի մի կենդանի։' },
  { id: 'sa-043', category: 'everyday', text: 'Ասա մի կարմիր բան։' },
  { id: 'sa-044', category: 'everyday', text: 'Ասա մի դեղին բան։' },
  { id: 'sa-045', category: 'everyday', text: 'Ասա մի կանաչ բան։' },
  { id: 'sa-046', category: 'everyday', text: 'Ասա մի սպիտակ բան։' },
  { id: 'sa-047', category: 'everyday', text: 'Ասա մի սառը բան։' },
  { id: 'sa-048', category: 'everyday', text: 'Ասա մի տաք բան։' },
  { id: 'sa-049', category: 'everyday', text: 'Ասա մի քաղցր բան։' },
  { id: 'sa-050', category: 'everyday', text: 'Ասա մի կլոր բան։' },
  { id: 'sa-051', category: 'objects', text: 'Ասա մի բան, որ խոհանոցում է լինում։' },
  { id: 'sa-052', category: 'objects', text: 'Ասա մի բան, որ լոգարանում է լինում։' },
  { id: 'sa-053', category: 'objects', text: 'Ասա մի բան, որ դպրոցական պայուսակում է լինում։' },
  { id: 'sa-054', category: 'objects', text: 'Ասա մի բան, որ ոտքին են հագնում։' },
  { id: 'sa-055', category: 'objects', text: 'Ասա մի բան, որ ձմռանն են հագնում։' },
  { id: 'sa-056', category: 'objects', text: 'Ասա մի բան, որ ծով են տանում։' },
  { id: 'sa-057', category: 'objects', text: 'Ասա մի կահույք։' },
  { id: 'sa-058', category: 'objects', text: 'Ասա մի բան, որ դրամապանակում է լինում։' },
  { id: 'sa-059', category: 'objects', text: 'Ասա մի բան, որ գրպանում են պահում։' },
  { id: 'sa-060', category: 'objects', text: 'Ասա մի բան, որ սառնարանում է լինում։' },
  { id: 'sa-061', category: 'objects', text: 'Ասա մեքենայի մի մաս։' },
  { id: 'sa-062', category: 'objects', text: 'Ասա մի գործիք։' },
  { id: 'sa-063', category: 'technology', text: 'Ասա մի բան, որ մարտկոցով է աշխատում։' },
  { id: 'sa-064', category: 'everyday', text: 'Ասա մի բան, որ ամեն առավոտ են օգտագործում։' },
  { id: 'sa-065', category: 'everyday', text: 'Ասա մարմնի մի մաս։' },
  { id: 'sa-066', category: 'everyday', text: 'Ասա մի երկրաչափական պատկեր։' },
  { id: 'sa-067', category: 'everyday', text: 'Ասա մի դպրոցական առարկա։' },
  { id: 'sa-068', category: 'everyday', text: 'Ասա մի մասնագիտություն։' },
  { id: 'sa-069', category: 'objects', text: 'Ասա անիվներով մի բան։' },
  { id: 'sa-070', category: 'objects', text: 'Ասա մի բան, որ դեղատնից են գնում։' },
  { id: 'sa-071', category: 'places', text: 'Ասա Եվրոպայի մի երկիր։' },
  { id: 'sa-072', category: 'social', text: 'Ասա մի բան, որ պիկնիկի են տանում։' },
  { id: 'sa-073', category: 'places', text: 'Ասա մի տեղ, ուր առաջին ժամադրության են գնում։' },
  { id: 'sa-074', category: 'travel', text: 'Ասա մի բան, որ ճամպրուկի մեջ են դնում։' },
  { id: 'sa-075', category: 'travel', text: 'Ասա տրանսպորտի մի տեսակ։' },
  { id: 'sa-076', category: 'travel', text: 'Ասա մի բան, որ օդանավակայանում է լինում։' },
  { id: 'sa-077', category: 'travel', text: 'Ասա մի տեղ Հայաստանում, ուր հանգստանալու են գնում։' },
  { id: 'sa-078', category: 'places', text: 'Ասա մի լեզու։' },
  { id: 'sa-079', category: 'places', text: 'Ասա մի մայրցամաք։' },
  { id: 'sa-080', category: 'places', text: 'Ասա մի տեղ, ուր միշտ շատ մարդ է լինում։' },
  { id: 'sa-081', category: 'places', text: 'Ասա մի բան, որ այգում է լինում։' },
  { id: 'sa-082', category: 'technology', text: 'Ասա մի սոցիալական ցանց։' },
  { id: 'sa-083', category: 'entertainment', text: 'Ասա մի սպորտաձև։' },
  { id: 'sa-084', category: 'entertainment', text: 'Ասա մի սեղանի խաղ։' },
  { id: 'sa-085', category: 'entertainment', text: 'Ասա մի սուպերհերոս։' },
  { id: 'sa-086', category: 'entertainment', text: 'Ասա մուլտֆիլմի մի հերոս։' },
  { id: 'sa-087', category: 'entertainment', text: 'Ասա մի երաժշտական գործիք։' },
  { id: 'sa-088', category: 'food', text: 'Ասա մի բան, որ քեֆին ուտում են։' },
  { id: 'sa-089', category: 'technology', text: 'Ասա հեռախոսի մի բրենդ։' },
  { id: 'sa-090', category: 'technology', text: 'Ասա մեքենայի մի մակնիշ։' },
  { id: 'sa-091', category: 'everyday', text: 'Ասա մի գույն, որ մարդիկ հաճախ են հագնում։' },
  { id: 'sa-092', category: 'entertainment', text: 'Ասա մի ֆիլմ, որ բոլորը տեսել են։' },
  { id: 'sa-093', category: 'technology', text: 'Ասա մի մեսենջեր։' },
  { id: 'sa-094', category: 'entertainment', text: 'Ասա երաժշտական մի ժանր։' },
  { id: 'sa-095', category: 'social', text: 'Ասա մի բան, որ անում են, երբ քունը չի տանում։' },
  { id: 'sa-096', category: 'entertainment', text: 'Ասա մի մանկական խաղ։' },
  { id: 'sa-097', category: 'social', text: 'Ասա ուշանալու մի պատճառ։' },
  { id: 'sa-098', category: 'social', text: 'Ասա տոնելու մի առիթ։' },
  { id: 'sa-099', category: 'social', text: 'Ասա մի բան, որ հարսանիքին են անում։' },
  { id: 'sa-100', category: 'social', text: 'Ասա ծննդյան մի նվեր։' },

  // Second hundred — same voice, new ground: senses, materials, places and habits.
  { id: 'sa-101', category: 'food', text: 'Ասա մի սառը ըմպելիք։' },
  { id: 'sa-102', category: 'food', text: 'Ասա մի աղի բան։' },
  { id: 'sa-103', category: 'food', text: 'Ասա մի թթու բան։' },
  { id: 'sa-104', category: 'food', text: 'Ասա մի կծու բան։' },
  { id: 'sa-105', category: 'food', text: 'Ասա մի բան, որ տապակում են։' },
  { id: 'sa-106', category: 'food', text: 'Ասա մի բան, որ շուկայից են գնում։' },
  { id: 'sa-107', category: 'food', text: 'Ասա մի չիր։' },
  { id: 'sa-108', category: 'food', text: 'Ասա մի բան, որ բրնձով են սարքում։' },
  { id: 'sa-109', category: 'food', text: 'Ասա մի բան, որ մրգից են սարքում։' },
  { id: 'sa-110', category: 'food', text: 'Ասա մի բան, որ կինոյում են ուտում։' },
  { id: 'sa-111', category: 'food', text: 'Ասա մի բան, որ ձվով են սարքում։' },
  { id: 'sa-112', category: 'food', text: 'Ասա մի բան, որ լավաշի մեջ են փաթաթում։' },
  { id: 'sa-113', category: 'food', text: 'Ասա մի բան, որ խմորից են սարքում։' },
  { id: 'sa-114', category: 'food', text: 'Ասա մի բան, որ սալաթի մեջ են դնում։' },
  { id: 'sa-115', category: 'food', text: 'Ասա մի բան, որ բուրգերի մեջ են դնում։' },
  { id: 'sa-116', category: 'armenia', text: 'Ասա մի հայկական հեռուստաալիք։' },
  { id: 'sa-117', category: 'armenia', text: 'Ասա մի հայ գրող։' },
  { id: 'sa-118', category: 'armenia', text: 'Ասա մի հայկական լեռ։' },
  { id: 'sa-119', category: 'armenia', text: 'Ասա մի հայկական գետ։' },
  { id: 'sa-120', category: 'armenia', text: 'Ասա Երևանի մի փողոց։' },
  { id: 'sa-121', category: 'armenia', text: 'Ասա Հայաստանի մի մարզ։' },
  { id: 'sa-122', category: 'armenia', text: 'Ասա մի հայկական պանիր։' },
  { id: 'sa-123', category: 'armenia', text: 'Ասա մի հայ դերասան։' },
  { id: 'sa-124', category: 'armenia', text: 'Ասա մի հայկական ֆիլմ։' },
  { id: 'sa-125', category: 'armenia', text: 'Ասա մի հայկական հանքային ջուր։' },
  { id: 'sa-126', category: 'animals', text: 'Ասա մի կենդանի, որ ձմռանը քնում է։' },
  { id: 'sa-127', category: 'animals', text: 'Ասա մի կենդանի, որ ծառի վրա է ապրում։' },
  { id: 'sa-128', category: 'animals', text: 'Ասա մի կենդանի, որ արագ է վազում։' },
  { id: 'sa-129', category: 'animals', text: 'Ասա մի կենդանի, որ դանդաղ է շարժվում։' },
  { id: 'sa-130', category: 'animals', text: 'Ասա մի կենդանի, որ կաթ է տալիս։' },
  { id: 'sa-131', category: 'animals', text: 'Ասա մի կենդանի, որ ձու է ածում։' },
  { id: 'sa-132', category: 'animals', text: 'Ասա մի կենդանի, որ լողում է։' },
  { id: 'sa-133', category: 'animals', text: 'Ասա մի կենդանի, որ գիշերն է արթուն։' },
  { id: 'sa-134', category: 'animals', text: 'Ասա մի կենդանի, որ ցատկում է։' },
  { id: 'sa-135', category: 'animals', text: 'Ասա մի կենդանի, որ եղջյուրներ ունի։' },
  { id: 'sa-136', category: 'everyday', text: 'Ասա մի սև բան։' },
  { id: 'sa-137', category: 'everyday', text: 'Ասա մի կապույտ բան։' },
  { id: 'sa-138', category: 'everyday', text: 'Ասա մի փափուկ բան։' },
  { id: 'sa-139', category: 'everyday', text: 'Ասա մի ծանր բան։' },
  { id: 'sa-140', category: 'everyday', text: 'Ասա մի բան, որ փայլում է։' },
  { id: 'sa-141', category: 'everyday', text: 'Ասա մի բան, որ արագ է։' },
  { id: 'sa-142', category: 'everyday', text: 'Ասա մի բան, որ բարձր ձայն է հանում։' },
  { id: 'sa-143', category: 'everyday', text: 'Ասա մի բան, որ երկնքում է լինում։' },
  { id: 'sa-144', category: 'everyday', text: 'Ասա մի բան, որ ամեն երեկո են անում։' },
  { id: 'sa-145', category: 'everyday', text: 'Ասա մի բան, որ շաբաթ-կիրակի են անում։' },
  { id: 'sa-146', category: 'everyday', text: 'Ասա մի բան, որ մոռանում են տանը։' },
  { id: 'sa-147', category: 'everyday', text: 'Ասա մի բան, որ ամեն օր խանութից են գնում։' },
  { id: 'sa-148', category: 'everyday', text: 'Ասա մի բան, որ մայրիկները միշտ ասում են։' },
  { id: 'sa-149', category: 'everyday', text: 'Ասա մի բան, որ ամռանն են անում։' },
  { id: 'sa-150', category: 'everyday', text: 'Ասա մի բան, որ ձմռանն են անում։' },
  { id: 'sa-151', category: 'everyday', text: 'Ասա մի բան, որ մարզասրահում են անում։' },
  { id: 'sa-152', category: 'everyday', text: 'Ասա մի բան, որ շատ թանկ է։' },
  { id: 'sa-153', category: 'everyday', text: 'Ասա մի բան, որ անվճար է։' },
  { id: 'sa-154', category: 'everyday', text: 'Ասա մի բան, որ երբեք բավական չի լինում։' },
  { id: 'sa-155', category: 'everyday', text: 'Ասա մի բան, որ երեխաները չեն սիրում։' },
  { id: 'sa-156', category: 'objects', text: 'Ասա մի բան, որ ննջասենյակում է լինում։' },
  { id: 'sa-157', category: 'objects', text: 'Ասա մի բան, որ պատից են կախում։' },
  { id: 'sa-158', category: 'objects', text: 'Ասա մի բան, որ բանալիով է բացվում։' },
  { id: 'sa-159', category: 'objects', text: 'Ասա մի բան, որ ապակուց է։' },
  { id: 'sa-160', category: 'objects', text: 'Ասա մի բան, որ փայտից է։' },
  { id: 'sa-161', category: 'objects', text: 'Ասա մի բան, որ մետաղից է։' },
  { id: 'sa-162', category: 'objects', text: 'Ասա մի բան, որ գլխին են դնում։' },
  { id: 'sa-163', category: 'objects', text: 'Ասա մի բան, որ ձեռքին են կրում։' },
  { id: 'sa-164', category: 'objects', text: 'Ասա մի բան, որ մեքենայի մեջ են պահում։' },
  { id: 'sa-165', category: 'objects', text: 'Ասա մի բան, որ երեխայի սենյակում է լինում։' },
  { id: 'sa-166', category: 'objects', text: 'Ասա մի բան, որ հոսանքով է աշխատում։' },
  { id: 'sa-167', category: 'objects', text: 'Ասա մի բան, որ մկրատով են կտրում։' },
  { id: 'sa-168', category: 'objects', text: 'Ասա մի բան, որ լվանում են։' },
  { id: 'sa-169', category: 'objects', text: 'Ասա մի բան, որ շշով են ծախում։' },
  { id: 'sa-170', category: 'technology', text: 'Ասա մի բան, որ էկրան ունի։' },
  { id: 'sa-171', category: 'social', text: 'Ասա մի բան, որ բոլորը լուսանկարում են։' },
  { id: 'sa-172', category: 'food', text: 'Ասա մի բան, որ շուտ է փչանում։' },
  { id: 'sa-173', category: 'technology', text: 'Ասա մի հայտնի կայք։' },
  { id: 'sa-174', category: 'technology', text: 'Ասա մի բան, որ հեռախոսով են անում։' },
  { id: 'sa-175', category: 'technology', text: 'Ասա համակարգչի մի մաս։' },
  { id: 'sa-176', category: 'places', text: 'Ասա մի տեղ, ուր հերթ են կանգնում։' },
  { id: 'sa-177', category: 'places', text: 'Ասա մի տեղ, ուր լուռ պետք է լինել։' },
  { id: 'sa-178', category: 'places', text: 'Ասա մի տեղ, ուր երեխաները սիրում են գնալ։' },
  { id: 'sa-179', category: 'places', text: 'Ասա մի տեղ, ուր ուտելիք են ծախում։' },
  { id: 'sa-180', category: 'places', text: 'Ասա Ասիայի մի երկիր։' },
  { id: 'sa-181', category: 'places', text: 'Ասա մի մեծ երկիր։' },
  { id: 'sa-182', category: 'places', text: 'Ասա մի մայրաքաղաք։' },
  { id: 'sa-183', category: 'places', text: 'Ասա մի տեղ, ուր տոմս են գնում։' },
  { id: 'sa-184', category: 'places', text: 'Ասա մի տեղ, ուր սովորում են։' },
  { id: 'sa-185', category: 'places', text: 'Ասա մի տեղ, ուր ընկերների հետ են հանդիպում։' },
  { id: 'sa-186', category: 'entertainment', text: 'Ասա մի բան, որ երեկոյան են դիտում։' },
  { id: 'sa-187', category: 'entertainment', text: 'Ասա մի հայտնի սերիալ։' },
  { id: 'sa-188', category: 'entertainment', text: 'Ասա մի թղթախաղ։' },
  { id: 'sa-189', category: 'entertainment', text: 'Ասա մի ձմեռային սպորտաձև։' },
  { id: 'sa-190', category: 'entertainment', text: 'Ասա մի հայտնի ֆուտբոլիստ։' },
  { id: 'sa-191', category: 'entertainment', text: 'Ասա մի բան, որ համերգին են անում։' },
  { id: 'sa-192', category: 'entertainment', text: 'Ասա հեքիաթի մի հերոս։' },
  { id: 'sa-193', category: 'entertainment', text: 'Ասա մի բան, որ ֆիլմերում միշտ լինում է։' },
  { id: 'sa-194', category: 'entertainment', text: 'Ասա մի բան, որ երաժշտության տակ են անում։' },
  { id: 'sa-195', category: 'entertainment', text: 'Ասա մի բան, որ մրցույթում են շահում։' },
  { id: 'sa-196', category: 'social', text: 'Ասա մի բան, որ Ամանորին խոստանում են։' },
  { id: 'sa-197', category: 'social', text: 'Ասա մի բան, որ գնալիս են ասում։' },
  { id: 'sa-198', category: 'social', text: 'Ասա մի բան, որի համար ներողություն են խնդրում։' },
  { id: 'sa-199', category: 'social', text: 'Ասա մի բան, որ մարդկանց ուրախացնում է։' },
  { id: 'sa-200', category: 'social', text: 'Ասա մի բան, որ մարդկանց նյարդայնացնում է։' },
];
