import type { Prompt } from './types';

/**
 * Same Answer deck — 100 prompts, paired 1:1 with the English ids.
 * Spoken Eastern Armenian, the way you would say it across a table: «Ասա մի…».
 * A handful of obvious answers each, nothing to argue about, nothing political.
 */
export const sameAnswerHy: Prompt[] = [
  { id: 'sa-001', category: 'food', text: 'Ասա մի հայկական ուտեստ։' },
  { id: 'sa-002', category: 'food', text: 'Ասա մի միրգ։' },
  { id: 'sa-003', category: 'food', text: 'Ասա մի բանջարեղեն։' },
  { id: 'sa-004', category: 'food', text: 'Ասա մի բան, որ նախաճաշին են ուտում։' },
  { id: 'sa-005', category: 'food', text: 'Ասա մի բան, որ պիցցայի վրա են դնում։' },
  { id: 'sa-006', category: 'food', text: 'Ասա մի տաք ըմպելիք։' },
  { id: 'sa-007', category: 'food', text: 'Ասա մի դեսերտ։' },
  { id: 'sa-008', category: 'food', text: 'Ասա մի կաթնամթերք։' },
  { id: 'sa-009', category: 'food', text: 'Ասա մի ֆաստ ֆուդ։' },
  { id: 'sa-010', category: 'food', text: 'Ասա մի կանաչի։' },
  { id: 'sa-011', category: 'food', text: 'Ասա մի բան, որ հացի վրա են քսում։' },
  { id: 'sa-012', category: 'food', text: 'Ասա մի բան, որ թեյի մեջ են դնում։' },
  { id: 'sa-013', category: 'food', text: 'Ասա պաղպաղակի մի համ։' },
  { id: 'sa-014', category: 'food', text: 'Ասա մի հայկական քաղցրավենիք։' },
  { id: 'sa-015', category: 'food', text: 'Ասա մի ապուր։' },
  { id: 'sa-016', category: 'food', text: 'Ասա մի ամառային միրգ։' },
  { id: 'sa-017', category: 'food', text: 'Ասա մի հյութ։' },
  { id: 'sa-018', category: 'food', text: 'Ասա մի բան, որ խորովում են։' },
  { id: 'sa-019', category: 'armenia', text: 'Ասա մի հայկական քաղաք։' },
  { id: 'sa-020', category: 'armenia', text: 'Ասա մի հայ երգիչ։' },
  { id: 'sa-021', category: 'food', text: 'Ասա մի բան, որ Ամանորի սեղանին է լինում։' },
  { id: 'sa-022', category: 'armenia', text: 'Ասա Երևանի մի վայր։' },
  { id: 'sa-023', category: 'armenia', text: 'Ասա մի հայկական տոն։' },
  { id: 'sa-024', category: 'everyday', text: 'Ասա մի ծաղիկ։' },
  { id: 'sa-025', category: 'entertainment', text: 'Ասա մի խաղալիք։' },
  { id: 'sa-026', category: 'armenia', text: 'Ասա մի հայկական պար։' },
  { id: 'sa-027', category: 'food', text: 'Ասա մի բան, որ փռից են գնում։' },
  { id: 'sa-028', category: 'objects', text: 'Ասա մի բան, որ գրասենյակում է լինում։' },
  { id: 'sa-029', category: 'armenia', text: 'Ասա մի հայկական բրենդ։' },
  { id: 'sa-030', category: 'social', text: 'Ասա մի բան, որից մարդիկ վախենում են։' },
  { id: 'sa-031', category: 'armenia', text: 'Ասա մի հայկական վանք։' },
  { id: 'sa-032', category: 'everyday', text: 'Ասա մի տնային գործ։' },
  { id: 'sa-033', category: 'animals', text: 'Ասա մի կենդանի, որ տանը պահում են։' },
  { id: 'sa-034', category: 'animals', text: 'Ասա մի կենդանի, որ գյուղում պահում են։' },
  { id: 'sa-035', category: 'animals', text: 'Ասա մի վայրի կենդանի։' },
  { id: 'sa-036', category: 'animals', text: 'Ասա մի թռչուն։' },
  { id: 'sa-037', category: 'animals', text: 'Ասա մի կենդանի, որ ծովում է ապրում։' },
  { id: 'sa-038', category: 'animals', text: 'Ասա մի միջատ։' },
  { id: 'sa-039', category: 'animals', text: 'Ասա մի գծավոր կենդանի։' },
  { id: 'sa-040', category: 'animals', text: 'Ասա կենդանաբանական այգու մի կենդանի։' },
  { id: 'sa-041', category: 'everyday', text: 'Ասա մի բան, որ լավ հոտ ունի։' },
  { id: 'sa-042', category: 'animals', text: 'Ասա հեքիաթի մի կենդանի։' },
  { id: 'sa-043', category: 'everyday', text: 'Ասա մի կարմիր բան։' },
  { id: 'sa-044', category: 'everyday', text: 'Ասա մի դեղին բան։' },
  { id: 'sa-045', category: 'everyday', text: 'Ասա մի կանաչ բան։' },
  { id: 'sa-046', category: 'everyday', text: 'Ասա մի սպիտակ բան։' },
  { id: 'sa-047', category: 'everyday', text: 'Ասա մի սառը բան։' },
  { id: 'sa-048', category: 'everyday', text: 'Ասա մի տաք բան։' },
  { id: 'sa-049', category: 'everyday', text: 'Ասա մի քաղցր բան։' },
  { id: 'sa-050', category: 'everyday', text: 'Ասա մի կլոր բան։' },
  { id: 'sa-051', category: 'objects', text: 'Ասա մի բան, որ խոհանոցում է լինում։' },
  { id: 'sa-052', category: 'objects', text: 'Ասա մի բան, որ լոգարանում է լինում։' },
  { id: 'sa-053', category: 'objects', text: 'Ասա մի բան, որ դպրոցի պայուսակում է լինում։' },
  { id: 'sa-054', category: 'objects', text: 'Ասա մի բան, որ ոտքին են հագնում։' },
  { id: 'sa-055', category: 'objects', text: 'Ասա մի բան, որ ձմռանն են հագնում։' },
  { id: 'sa-056', category: 'objects', text: 'Ասա մի բան, որ ծով են տանում։' },
  { id: 'sa-057', category: 'objects', text: 'Ասա կահույքի մի կտոր։' },
  { id: 'sa-058', category: 'objects', text: 'Ասա մի բան, որ դրամապանակում է լինում։' },
  { id: 'sa-059', category: 'objects', text: 'Ասա մի բան, որ գրպանում են պահում։' },
  { id: 'sa-060', category: 'objects', text: 'Ասա մի բան, որ սառնարանում է լինում։' },
  { id: 'sa-061', category: 'objects', text: 'Ասա մեքենայի մի մաս։' },
  { id: 'sa-062', category: 'objects', text: 'Ասա մի գործիք։' },
  { id: 'sa-063', category: 'technology', text: 'Ասա մի բան, որ մարտկոցով է աշխատում։' },
  { id: 'sa-064', category: 'everyday', text: 'Ասա մի բան, որ ամեն առավոտ ես օգտագործում։' },
  { id: 'sa-065', category: 'everyday', text: 'Ասա մարմնի մի մաս։' },
  { id: 'sa-066', category: 'everyday', text: 'Ասա մի երկրաչափական պատկեր։' },
  { id: 'sa-067', category: 'everyday', text: 'Ասա մի դպրոցական առարկա։' },
  { id: 'sa-068', category: 'everyday', text: 'Ասա մի մասնագիտություն։' },
  { id: 'sa-069', category: 'objects', text: 'Ասա անիվներով մի բան։' },
  { id: 'sa-070', category: 'objects', text: 'Ասա մի բան, որ դեղատնից են գնում։' },
  { id: 'sa-071', category: 'places', text: 'Ասա Եվրոպայի մի երկիր։' },
  { id: 'sa-072', category: 'social', text: 'Ասա մի բան, որ պիկնիկի են տանում։' },
  { id: 'sa-073', category: 'places', text: 'Ասա մի տեղ, ուր առաջին ժամադրության են գնում։' },
  { id: 'sa-074', category: 'travel', text: 'Ասա մի բան, որ ճամպրուկի մեջ են դնում։' },
  { id: 'sa-075', category: 'travel', text: 'Ասա մի տրանսպորտի տեսակ։' },
  { id: 'sa-076', category: 'travel', text: 'Ասա մի բան, որ օդանավակայանում է լինում։' },
  { id: 'sa-077', category: 'travel', text: 'Ասա մի տեղ Հայաստանում, ուր հանգստանալու են գնում։' },
  { id: 'sa-078', category: 'places', text: 'Ասա մի լեզու։' },
  { id: 'sa-079', category: 'places', text: 'Ասա մի մայրցամաք։' },
  { id: 'sa-080', category: 'places', text: 'Ասա մի տեղ, ուր միշտ շատ մարդ է լինում։' },
  { id: 'sa-081', category: 'places', text: 'Ասա մի բան, որ այգում ես տեսնում։' },
  { id: 'sa-082', category: 'technology', text: 'Ասա մի սոցիալական ցանց։' },
  { id: 'sa-083', category: 'entertainment', text: 'Ասա մի սպորտաձև։' },
  { id: 'sa-084', category: 'entertainment', text: 'Ասա մի սեղանի խաղ։' },
  { id: 'sa-085', category: 'entertainment', text: 'Ասա մի սուպերհերոս։' },
  { id: 'sa-086', category: 'entertainment', text: 'Ասա մուլտֆիլմի մի հերոս։' },
  { id: 'sa-087', category: 'entertainment', text: 'Ասա մի երաժշտական գործիք։' },
  { id: 'sa-088', category: 'food', text: 'Ասա մի բան, որ քեֆին ուտում են։' },
  { id: 'sa-089', category: 'technology', text: 'Ասա հեռախոսի մի բրենդ։' },
  { id: 'sa-090', category: 'technology', text: 'Ասա մեքենայի մի մակնիշ։' },
  { id: 'sa-091', category: 'everyday', text: 'Ասա մի գույն, որ մարդիկ հաճախ են հագնում։' },
  { id: 'sa-092', category: 'entertainment', text: 'Ասա մի ֆիլմ, որ բոլորը տեսել են։' },
  { id: 'sa-093', category: 'technology', text: 'Ասա մի մեսենջեր։' },
  { id: 'sa-094', category: 'entertainment', text: 'Ասա երաժշտական մի ժանր։' },
  { id: 'sa-095', category: 'social', text: 'Ասա մի բան, որ անում են, երբ քունը չի տանում։' },
  { id: 'sa-096', category: 'entertainment', text: 'Ասա մի մանկական խաղ։' },
  { id: 'sa-097', category: 'social', text: 'Ասա ուշանալու մի պատճառ։' },
  { id: 'sa-098', category: 'social', text: 'Ասա տոնելու մի առիթ։' },
  { id: 'sa-099', category: 'social', text: 'Ասա մի բան, որ հարսանիքին են անում։' },
  { id: 'sa-100', category: 'social', text: 'Ասա ծննդյան մի նվեր։' },
];
