import type { Card } from './types';

/**
 * Act It! deck — 200 cards.
 * Rules for every card: one word (a two-word concept only when there is no single word), easy
 * to act with the body, easy to guess, nothing abstract, nothing that needs trivia.
 * Ids are shared with `hy.ts`; add a card to both files or to neither.
 */
export const actItEn: Card[] = [
  { id: 'ai-001', category: 'action', text: 'Sleeping' },
  { id: 'ai-002', category: 'action', text: 'Swimming' },
  { id: 'ai-003', category: 'action', text: 'Running' },
  { id: 'ai-004', category: 'action', text: 'Cooking' },
  { id: 'ai-005', category: 'action', text: 'Dancing' },
  { id: 'ai-006', category: 'action', text: 'Fishing' },
  { id: 'ai-007', category: 'action', text: 'Driving' },
  { id: 'ai-008', category: 'action', text: 'Crying' },
  { id: 'ai-009', category: 'action', text: 'Laughing' },
  { id: 'ai-010', category: 'action', text: 'Sweeping' },
  { id: 'ai-011', category: 'action', text: 'Eating' },
  { id: 'ai-012', category: 'action', text: 'Drinking' },
  { id: 'ai-013', category: 'action', text: 'Reading' },
  { id: 'ai-014', category: 'action', text: 'Singing' },
  { id: 'ai-015', category: 'action', text: 'Jumping' },
  { id: 'ai-016', category: 'action', text: 'Climbing' },
  { id: 'ai-017', category: 'action', text: 'Falling' },
  { id: 'ai-018', category: 'action', text: 'Sneezing' },
  { id: 'ai-019', category: 'action', text: 'Yawning' },
  { id: 'ai-020', category: 'action', text: 'Hugging' },
  { id: 'ai-021', category: 'action', text: 'Waving' },
  { id: 'ai-022', category: 'action', text: 'Clapping' },
  { id: 'ai-023', category: 'action', text: 'Knocking' },
  { id: 'ai-024', category: 'action', text: 'Drawing' },
  { id: 'ai-025', category: 'action', text: 'Texting' },
  { id: 'ai-026', category: 'action', text: 'Calling' },
  { id: 'ai-027', category: 'action', text: 'Shopping' },
  { id: 'ai-028', category: 'action', text: 'Praying' },
  { id: 'ai-029', category: 'action', text: 'Shaving' },
  { id: 'ai-030', category: 'action', text: 'Brushing teeth' },
  { id: 'ai-031', category: 'action', text: 'Showering' },
  { id: 'ai-032', category: 'action', text: 'Combing hair' },
  { id: 'ai-033', category: 'action', text: 'Ironing' },
  { id: 'ai-034', category: 'action', text: 'Washing dishes' },
  { id: 'ai-035', category: 'action', text: 'Hiding' },
  { id: 'ai-036', category: 'action', text: 'Searching' },
  { id: 'ai-037', category: 'action', text: 'Sewing' },
  { id: 'ai-038', category: 'action', text: 'Knitting' },
  { id: 'ai-039', category: 'action', text: 'Milking a cow' },
  { id: 'ai-040', category: 'action', text: 'Tickling' },
  { id: 'ai-041', category: 'action', text: 'Sunbathing' },
  { id: 'ai-042', category: 'action', text: 'Hiccups' },
  { id: 'ai-043', category: 'action', text: 'Tying shoes' },
  { id: 'ai-044', category: 'action', text: 'Kneading dough' },
  { id: 'ai-045', category: 'action', text: 'Hammering' },
  { id: 'ai-046', category: 'action', text: 'Kissing' },
  { id: 'ai-047', category: 'action', text: 'Marriage proposal' },
  { id: 'ai-048', category: 'action', text: 'Hitchhiking' },
  { id: 'ai-049', category: 'action', text: 'Selfie' },
  { id: 'ai-050', category: 'action', text: 'Tug of war' },
  { id: 'ai-051', category: 'animal', text: 'Cat' },
  { id: 'ai-052', category: 'animal', text: 'Dog' },
  { id: 'ai-053', category: 'animal', text: 'Monkey' },
  { id: 'ai-054', category: 'animal', text: 'Elephant' },
  { id: 'ai-055', category: 'animal', text: 'Rabbit' },
  { id: 'ai-056', category: 'animal', text: 'Chicken' },
  { id: 'ai-057', category: 'animal', text: 'Cow' },
  { id: 'ai-058', category: 'animal', text: 'Horse' },
  { id: 'ai-059', category: 'animal', text: 'Snake' },
  { id: 'ai-060', category: 'animal', text: 'Frog' },
  { id: 'ai-061', category: 'animal', text: 'Hedgehog' },
  { id: 'ai-062', category: 'animal', text: 'Lion' },
  { id: 'ai-063', category: 'animal', text: 'Bear' },
  { id: 'ai-064', category: 'animal', text: 'Kangaroo' },
  { id: 'ai-065', category: 'animal', text: 'Penguin' },
  { id: 'ai-066', category: 'animal', text: 'Flamingo' },
  { id: 'ai-067', category: 'animal', text: 'Giraffe' },
  { id: 'ai-068', category: 'animal', text: 'Mouse' },
  { id: 'ai-069', category: 'animal', text: 'Spider' },
  { id: 'ai-070', category: 'animal', text: 'Bee' },
  { id: 'ai-071', category: 'animal', text: 'Butterfly' },
  { id: 'ai-072', category: 'animal', text: 'Turtle' },
  { id: 'ai-073', category: 'animal', text: 'Sheep' },
  { id: 'ai-074', category: 'animal', text: 'Pig' },
  { id: 'ai-075', category: 'animal', text: 'Donkey' },
  { id: 'ai-076', category: 'animal', text: 'Crocodile' },
  { id: 'ai-077', category: 'animal', text: 'Shark' },
  { id: 'ai-078', category: 'animal', text: 'Owl' },
  { id: 'ai-079', category: 'animal', text: 'Camel' },
  { id: 'ai-080', category: 'animal', text: 'Duck' },
  { id: 'ai-081', category: 'animal', text: 'Peacock' },
  { id: 'ai-082', category: 'animal', text: 'Octopus' },
  { id: 'ai-083', category: 'animal', text: 'Mosquito' },
  { id: 'ai-084', category: 'animal', text: 'Crab' },
  { id: 'ai-085', category: 'animal', text: 'Dinosaur' },
  { id: 'ai-086', category: 'animal', text: 'Squirrel' },
  { id: 'ai-087', category: 'people', text: 'Doctor' },
  { id: 'ai-088', category: 'people', text: 'Teacher' },
  { id: 'ai-089', category: 'people', text: 'Waiter' },
  { id: 'ai-090', category: 'people', text: 'Photographer' },
  { id: 'ai-091', category: 'people', text: 'Barber' },
  { id: 'ai-092', category: 'people', text: 'Police officer' },
  { id: 'ai-093', category: 'people', text: 'Firefighter' },
  { id: 'ai-094', category: 'people', text: 'Lifeguard' },
  { id: 'ai-095', category: 'people', text: 'Conductor' },
  { id: 'ai-096', category: 'people', text: 'Soldier' },
  { id: 'ai-097', category: 'people', text: 'Dentist' },
  { id: 'ai-098', category: 'people', text: 'Sculptor' },
  { id: 'ai-099', category: 'people', text: 'DJ' },
  { id: 'ai-100', category: 'people', text: 'Ballerina' },
  { id: 'ai-101', category: 'people', text: 'Magician' },
  { id: 'ai-102', category: 'people', text: 'Clown' },
  { id: 'ai-103', category: 'people', text: 'King' },
  { id: 'ai-104', category: 'people', text: 'Thief' },
  { id: 'ai-105', category: 'people', text: 'Baby' },
  { id: 'ai-106', category: 'people', text: 'Grandma' },
  { id: 'ai-107', category: 'people', text: 'Model' },
  { id: 'ai-108', category: 'people', text: 'Tamada' },
  { id: 'ai-109', category: 'people', text: 'Shepherd' },
  { id: 'ai-110', category: 'people', text: 'Goalkeeper' },
  { id: 'ai-111', category: 'people', text: 'Referee' },
  { id: 'ai-112', category: 'people', text: 'Mime' },
  { id: 'ai-113', category: 'people', text: 'Astronaut' },
  { id: 'ai-114', category: 'people', text: 'Robot' },
  { id: 'ai-115', category: 'people', text: 'Zombie' },
  { id: 'ai-116', category: 'people', text: 'Vampire' },
  { id: 'ai-117', category: 'people', text: 'Ghost' },
  { id: 'ai-118', category: 'people', text: 'Spider-Man' },
  { id: 'ai-119', category: 'people', text: 'Ninja' },
  { id: 'ai-120', category: 'people', text: 'Pirate' },
  { id: 'ai-121', category: 'people', text: 'Cowboy' },
  { id: 'ai-122', category: 'people', text: 'Mermaid' },
  { id: 'ai-123', category: 'people', text: 'Santa Claus' },
  { id: 'ai-124', category: 'people', text: 'Snowman' },
  { id: 'ai-125', category: 'people', text: 'Juggler' },
  { id: 'ai-126', category: 'people', text: 'Tightrope walker' },
  { id: 'ai-127', category: 'sport', text: 'Football' },
  { id: 'ai-128', category: 'sport', text: 'Basketball' },
  { id: 'ai-129', category: 'sport', text: 'Boxing' },
  { id: 'ai-130', category: 'sport', text: 'Skiing' },
  { id: 'ai-131', category: 'sport', text: 'Tennis' },
  { id: 'ai-132', category: 'sport', text: 'Volleyball' },
  { id: 'ai-133', category: 'sport', text: 'Golf' },
  { id: 'ai-134', category: 'sport', text: 'Bowling' },
  { id: 'ai-135', category: 'sport', text: 'Weightlifting' },
  { id: 'ai-136', category: 'sport', text: 'Wrestling' },
  { id: 'ai-137', category: 'sport', text: 'Karate' },
  { id: 'ai-138', category: 'sport', text: 'Yoga' },
  { id: 'ai-139', category: 'sport', text: 'Gymnastics' },
  { id: 'ai-140', category: 'sport', text: 'Rowing' },
  { id: 'ai-141', category: 'sport', text: 'Ice skating' },
  { id: 'ai-142', category: 'sport', text: 'Surfing' },
  { id: 'ai-143', category: 'sport', text: 'Archery' },
  { id: 'ai-144', category: 'sport', text: 'Fencing' },
  { id: 'ai-145', category: 'sport', text: 'Chess' },
  { id: 'ai-146', category: 'sport', text: 'Ping-pong' },
  { id: 'ai-147', category: 'sport', text: 'Hockey' },
  { id: 'ai-148', category: 'sport', text: 'Jump rope' },
  { id: 'ai-149', category: 'sport', text: 'Sumo' },
  { id: 'ai-150', category: 'sport', text: 'Scuba diving' },
  { id: 'ai-151', category: 'sport', text: 'Billiards' },
  { id: 'ai-152', category: 'sport', text: 'Arm wrestling' },
  { id: 'ai-153', category: 'sport', text: 'Sledding' },
  { id: 'ai-154', category: 'sport', text: 'Trampoline' },
  { id: 'ai-155', category: 'sport', text: 'Parachute' },
  { id: 'ai-156', category: 'sport', text: 'Skateboard' },
  { id: 'ai-157', category: 'armenia', text: 'Lavash' },
  { id: 'ai-158', category: 'armenia', text: 'Khorovats' },
  { id: 'ai-159', category: 'armenia', text: 'Rug beating' },
  { id: 'ai-160', category: 'armenia', text: 'Coffee' },
  { id: 'ai-161', category: 'armenia', text: 'Duduk' },
  { id: 'ai-162', category: 'armenia', text: 'Dhol' },
  { id: 'ai-163', category: 'armenia', text: 'Kanon' },
  { id: 'ai-164', category: 'armenia', text: 'Kochari' },
  { id: 'ai-165', category: 'action', text: 'Snowball fight' },
  { id: 'ai-166', category: 'armenia', text: 'Nardi' },
  { id: 'ai-167', category: 'armenia', text: 'Khash' },
  { id: 'ai-168', category: 'armenia', text: 'Sunflower seeds' },
  { id: 'ai-169', category: 'armenia', text: 'Marshrutka' },
  { id: 'ai-170', category: 'armenia', text: 'Vardavar' },
  { id: 'ai-171', category: 'armenia', text: 'Trndez' },
  { id: 'ai-172', category: 'armenia', text: 'Egg fight' },
  { id: 'ai-173', category: 'armenia', text: 'Wedding' },
  { id: 'ai-174', category: 'armenia', text: 'Birthday' },
  { id: 'ai-175', category: 'armenia', text: 'New Year' },
  { id: 'ai-176', category: 'armenia', text: 'Fortune telling' },
  { id: 'ai-177', category: 'object', text: 'Umbrella' },
  { id: 'ai-178', category: 'object', text: 'Guitar' },
  { id: 'ai-179', category: 'object', text: 'Piano' },
  { id: 'ai-180', category: 'object', text: 'Violin' },
  { id: 'ai-181', category: 'object', text: 'Scissors' },
  { id: 'ai-182', category: 'object', text: 'Key' },
  { id: 'ai-183', category: 'object', text: 'Glasses' },
  { id: 'ai-184', category: 'object', text: 'Bicycle' },
  { id: 'ai-185', category: 'object', text: 'Airplane' },
  { id: 'ai-186', category: 'object', text: 'Elevator' },
  { id: 'ai-187', category: 'object', text: 'Mirror' },
  { id: 'ai-188', category: 'object', text: 'Alarm clock' },
  { id: 'ai-189', category: 'object', text: 'Hair dryer' },
  { id: 'ai-190', category: 'object', text: 'Vacuum cleaner' },
  { id: 'ai-191', category: 'object', text: 'Remote control' },
  { id: 'ai-192', category: 'object', text: 'Balloon' },
  { id: 'ai-193', category: 'object', text: 'Lipstick' },
  { id: 'ai-194', category: 'object', text: 'Ice cream' },
  { id: 'ai-195', category: 'object', text: 'Watermelon' },
  { id: 'ai-196', category: 'object', text: 'Spaghetti' },
  { id: 'ai-197', category: 'object', text: 'Lemon' },
  { id: 'ai-198', category: 'object', text: 'Chewing gum' },
  { id: 'ai-199', category: 'object', text: 'Shawarma' },
  { id: 'ai-200', category: 'object', text: 'Traffic jam' },
];
