import type { Card } from './types';

/**
 * Act It! deck — 200 cards, paired 1:1 with the English ids.
 * Actions are infinitives («Քնել», «Պարել»), the rest are the everyday spoken word — «Պուլտ»,
 * «Սեմիչկա», «Մարշրուտկա» — not the dictionary one.
 */
export const actItHy: Card[] = [
  { id: 'ai-001', category: 'action', text: 'Քնել' },
  { id: 'ai-002', category: 'action', text: 'Լողալ' },
  { id: 'ai-003', category: 'action', text: 'Վազել' },
  { id: 'ai-004', category: 'action', text: 'Ճաշ եփել' },
  { id: 'ai-005', category: 'action', text: 'Պարել' },
  { id: 'ai-006', category: 'action', text: 'Ձուկ բռնել' },
  { id: 'ai-007', category: 'action', text: 'Մեքենա վարել' },
  { id: 'ai-008', category: 'action', text: 'Լացել' },
  { id: 'ai-009', category: 'action', text: 'Ծիծաղել' },
  { id: 'ai-010', category: 'action', text: 'Ավլել' },
  { id: 'ai-011', category: 'action', text: 'Ուտել' },
  { id: 'ai-012', category: 'action', text: 'Խմել' },
  { id: 'ai-013', category: 'action', text: 'Կարդալ' },
  { id: 'ai-014', category: 'action', text: 'Երգել' },
  { id: 'ai-015', category: 'action', text: 'Թռչկոտել' },
  { id: 'ai-016', category: 'action', text: 'Մագլցել' },
  { id: 'ai-017', category: 'action', text: 'Ընկնել' },
  { id: 'ai-018', category: 'action', text: 'Փռշտալ' },
  { id: 'ai-019', category: 'action', text: 'Հորանջել' },
  { id: 'ai-020', category: 'action', text: 'Գրկել' },
  { id: 'ai-021', category: 'action', text: 'Ձեռքով անել' },
  { id: 'ai-022', category: 'action', text: 'Ծափ տալ' },
  { id: 'ai-023', category: 'action', text: 'Դուռ թակել' },
  { id: 'ai-024', category: 'action', text: 'Մատիտով նկարել' },
  { id: 'ai-025', category: 'action', text: 'Մեսիջ գրել' },
  { id: 'ai-026', category: 'action', text: 'Զանգել' },
  { id: 'ai-027', category: 'action', text: 'Գնումներ անել' },
  { id: 'ai-028', category: 'action', text: 'Աղոթել' },
  { id: 'ai-029', category: 'action', text: 'Սափրվել' },
  { id: 'ai-030', category: 'action', text: 'Ատամ լվանալ' },
  { id: 'ai-031', category: 'action', text: 'Լողանալ' },
  { id: 'ai-032', category: 'action', text: 'Սանրվել' },
  { id: 'ai-033', category: 'action', text: 'Արդուկել' },
  { id: 'ai-034', category: 'action', text: 'Աման լվանալ' },
  { id: 'ai-035', category: 'action', text: 'Թաքնվել' },
  { id: 'ai-036', category: 'action', text: 'Փնտրել' },
  { id: 'ai-037', category: 'action', text: 'Կարել' },
  { id: 'ai-038', category: 'action', text: 'Շալ գործել' },
  { id: 'ai-039', category: 'action', text: 'Կով կթել' },
  { id: 'ai-040', category: 'action', text: 'Խտուտ տալ' },
  { id: 'ai-041', category: 'action', text: 'Արևայրուք ընդունել' },
  { id: 'ai-042', category: 'action', text: 'Զկռտալ' },
  { id: 'ai-043', category: 'action', text: 'Կոշիկ կապել' },
  { id: 'ai-044', category: 'action', text: 'Խմոր հունցել' },
  { id: 'ai-045', category: 'action', text: 'Մեխ խփել' },
  { id: 'ai-046', category: 'action', text: 'Համբուրել' },
  { id: 'ai-047', category: 'action', text: 'Ամուսնության առաջարկ' },
  { id: 'ai-048', category: 'action', text: 'Ավտոստոպ' },
  { id: 'ai-049', category: 'action', text: 'Սելֆի' },
  { id: 'ai-050', category: 'action', text: 'Պարան քաշել' },
  { id: 'ai-051', category: 'animal', text: 'Կատու' },
  { id: 'ai-052', category: 'animal', text: 'Շուն' },
  { id: 'ai-053', category: 'animal', text: 'Կապիկ' },
  { id: 'ai-054', category: 'animal', text: 'Փիղ' },
  { id: 'ai-055', category: 'animal', text: 'Նապաստակ' },
  { id: 'ai-056', category: 'animal', text: 'Հավ' },
  { id: 'ai-057', category: 'animal', text: 'Կով' },
  { id: 'ai-058', category: 'animal', text: 'Ձի' },
  { id: 'ai-059', category: 'animal', text: 'Օձ' },
  { id: 'ai-060', category: 'animal', text: 'Գորտ' },
  { id: 'ai-061', category: 'animal', text: 'Ոզնի' },
  { id: 'ai-062', category: 'animal', text: 'Առյուծ' },
  { id: 'ai-063', category: 'animal', text: 'Արջ' },
  { id: 'ai-064', category: 'animal', text: 'Կենգուրու' },
  { id: 'ai-065', category: 'animal', text: 'Պինգվին' },
  { id: 'ai-066', category: 'animal', text: 'Ֆլամինգո' },
  { id: 'ai-067', category: 'animal', text: 'Ընձուղտ' },
  { id: 'ai-068', category: 'animal', text: 'Մուկ' },
  { id: 'ai-069', category: 'animal', text: 'Սարդ' },
  { id: 'ai-070', category: 'animal', text: 'Մեղու' },
  { id: 'ai-071', category: 'animal', text: 'Թիթեռ' },
  { id: 'ai-072', category: 'animal', text: 'Կրիա' },
  { id: 'ai-073', category: 'animal', text: 'Ոչխար' },
  { id: 'ai-074', category: 'animal', text: 'Խոզ' },
  { id: 'ai-075', category: 'animal', text: 'Էշ' },
  { id: 'ai-076', category: 'animal', text: 'Կոկորդիլոս' },
  { id: 'ai-077', category: 'animal', text: 'Շնաձուկ' },
  { id: 'ai-078', category: 'animal', text: 'Բու' },
  { id: 'ai-079', category: 'animal', text: 'Ուղտ' },
  { id: 'ai-080', category: 'animal', text: 'Բադ' },
  { id: 'ai-081', category: 'animal', text: 'Սիրամարգ' },
  { id: 'ai-082', category: 'animal', text: 'Ութոտնուկ' },
  { id: 'ai-083', category: 'animal', text: 'Մոծակ' },
  { id: 'ai-084', category: 'animal', text: 'Խեցգետին' },
  { id: 'ai-085', category: 'animal', text: 'Դինոզավր' },
  { id: 'ai-086', category: 'animal', text: 'Սկյուռ' },
  { id: 'ai-087', category: 'people', text: 'Բժիշկ' },
  { id: 'ai-088', category: 'people', text: 'Ուսուցիչ' },
  { id: 'ai-089', category: 'people', text: 'Մատուցող' },
  { id: 'ai-090', category: 'people', text: 'Լուսանկարիչ' },
  { id: 'ai-091', category: 'people', text: 'Վարսավիր' },
  { id: 'ai-092', category: 'people', text: 'Ոստիկան' },
  { id: 'ai-093', category: 'people', text: 'Հրշեջ' },
  { id: 'ai-094', category: 'people', text: 'Փրկարար' },
  { id: 'ai-095', category: 'people', text: 'Դիրիժոր' },
  { id: 'ai-096', category: 'people', text: 'Զինվոր' },
  { id: 'ai-097', category: 'people', text: 'Ատամնաբույժ' },
  { id: 'ai-098', category: 'people', text: 'Քանդակագործ' },
  { id: 'ai-099', category: 'people', text: 'Դիջեյ' },
  { id: 'ai-100', category: 'people', text: 'Բալերինա' },
  { id: 'ai-101', category: 'people', text: 'Աճպարար' },
  { id: 'ai-102', category: 'people', text: 'Ծաղրածու' },
  { id: 'ai-103', category: 'people', text: 'Թագավոր' },
  { id: 'ai-104', category: 'people', text: 'Գող' },
  { id: 'ai-105', category: 'people', text: 'Երեխա' },
  { id: 'ai-106', category: 'people', text: 'Տատիկ' },
  { id: 'ai-107', category: 'people', text: 'Մոդել' },
  { id: 'ai-108', category: 'people', text: 'Թամադա' },
  { id: 'ai-109', category: 'people', text: 'Հովիվ' },
  { id: 'ai-110', category: 'people', text: 'Դարպասապահ' },
  { id: 'ai-111', category: 'people', text: 'Մրցավար' },
  { id: 'ai-112', category: 'people', text: 'Միմ' },
  { id: 'ai-113', category: 'people', text: 'Տիեզերագնաց' },
  { id: 'ai-114', category: 'people', text: 'Ռոբոտ' },
  { id: 'ai-115', category: 'people', text: 'Զոմբի' },
  { id: 'ai-116', category: 'people', text: 'Վամպիր' },
  { id: 'ai-117', category: 'people', text: 'Ուրվական' },
  { id: 'ai-118', category: 'people', text: 'Սփայդերմեն' },
  { id: 'ai-119', category: 'people', text: 'Նինձյա' },
  { id: 'ai-120', category: 'people', text: 'Ծովահեն' },
  { id: 'ai-121', category: 'people', text: 'Կովբոյ' },
  { id: 'ai-122', category: 'people', text: 'Ջրահարս' },
  { id: 'ai-123', category: 'people', text: 'Ձմեռ պապ' },
  { id: 'ai-124', category: 'people', text: 'Ձնեմարդ' },
  { id: 'ai-125', category: 'people', text: 'Ժոնգլյոր' },
  { id: 'ai-126', category: 'people', text: 'Լարախաղաց' },
  { id: 'ai-127', category: 'sport', text: 'Ֆուտբոլ' },
  { id: 'ai-128', category: 'sport', text: 'Բասկետբոլ' },
  { id: 'ai-129', category: 'sport', text: 'Բռնցքամարտ' },
  { id: 'ai-130', category: 'sport', text: 'Դահուկ' },
  { id: 'ai-131', category: 'sport', text: 'Թենիս' },
  { id: 'ai-132', category: 'sport', text: 'Վոլեյբոլ' },
  { id: 'ai-133', category: 'sport', text: 'Գոլֆ' },
  { id: 'ai-134', category: 'sport', text: 'Բոուլինգ' },
  { id: 'ai-135', category: 'sport', text: 'Ծանրամարտ' },
  { id: 'ai-136', category: 'sport', text: 'Ըմբշամարտ' },
  { id: 'ai-137', category: 'sport', text: 'Կարատե' },
  { id: 'ai-138', category: 'sport', text: 'Յոգա' },
  { id: 'ai-139', category: 'sport', text: 'Մարմնամարզություն' },
  { id: 'ai-140', category: 'sport', text: 'Թիավարել' },
  { id: 'ai-141', category: 'sport', text: 'Չմուշկ' },
  { id: 'ai-142', category: 'sport', text: 'Սերֆինգ' },
  { id: 'ai-143', category: 'sport', text: 'Նետաձգություն' },
  { id: 'ai-144', category: 'sport', text: 'Սուսերամարտ' },
  { id: 'ai-145', category: 'sport', text: 'Շախմատ' },
  { id: 'ai-146', category: 'sport', text: 'Պինգ-պոնգ' },
  { id: 'ai-147', category: 'sport', text: 'Հոկեյ' },
  { id: 'ai-148', category: 'sport', text: 'Ցատկապարան' },
  { id: 'ai-149', category: 'sport', text: 'Սումո' },
  { id: 'ai-150', category: 'sport', text: 'Ջրասուզակ' },
  { id: 'ai-151', category: 'sport', text: 'Բիլիարդ' },
  { id: 'ai-152', category: 'sport', text: 'Ձեռք ծալել' },
  { id: 'ai-153', category: 'sport', text: 'Սահնակ' },
  { id: 'ai-154', category: 'sport', text: 'Բատուտ' },
  { id: 'ai-155', category: 'sport', text: 'Պարաշյուտ' },
  { id: 'ai-156', category: 'sport', text: 'Սքեյթբորդ' },
  { id: 'ai-157', category: 'armenia', text: 'Լավաշ' },
  { id: 'ai-158', category: 'armenia', text: 'Խորոված' },
  { id: 'ai-159', category: 'armenia', text: 'Գորգ թափ տալ' },
  { id: 'ai-160', category: 'armenia', text: 'Սուրճ' },
  { id: 'ai-161', category: 'armenia', text: 'Դուդուկ' },
  { id: 'ai-162', category: 'armenia', text: 'Դհոլ' },
  { id: 'ai-163', category: 'armenia', text: 'Քանոն' },
  { id: 'ai-164', category: 'armenia', text: 'Քոչարի' },
  { id: 'ai-165', category: 'action', text: 'Ձնագնդի կռիվ' },
  { id: 'ai-166', category: 'armenia', text: 'Նարդի' },
  { id: 'ai-167', category: 'armenia', text: 'Խաշ' },
  { id: 'ai-168', category: 'armenia', text: 'Սեմիչկա' },
  { id: 'ai-169', category: 'armenia', text: 'Մարշրուտկա' },
  { id: 'ai-170', category: 'armenia', text: 'Վարդավառ' },
  { id: 'ai-171', category: 'armenia', text: 'Տրնդեզ' },
  { id: 'ai-172', category: 'armenia', text: 'Ձվակռիվ' },
  { id: 'ai-173', category: 'armenia', text: 'Հարսանիք' },
  { id: 'ai-174', category: 'armenia', text: 'Ծնունդ' },
  { id: 'ai-175', category: 'armenia', text: 'Ամանոր' },
  { id: 'ai-176', category: 'armenia', text: 'Բախտ նայել' },
  { id: 'ai-177', category: 'object', text: 'Անձրևանոց' },
  { id: 'ai-178', category: 'object', text: 'Կիթառ' },
  { id: 'ai-179', category: 'object', text: 'Դաշնամուր' },
  { id: 'ai-180', category: 'object', text: 'Ջութակ' },
  { id: 'ai-181', category: 'object', text: 'Մկրատ' },
  { id: 'ai-182', category: 'object', text: 'Բանալի' },
  { id: 'ai-183', category: 'object', text: 'Ակնոց' },
  { id: 'ai-184', category: 'object', text: 'Հեծանիվ' },
  { id: 'ai-185', category: 'object', text: 'Ինքնաթիռ' },
  { id: 'ai-186', category: 'object', text: 'Վերելակ' },
  { id: 'ai-187', category: 'object', text: 'Հայելի' },
  { id: 'ai-188', category: 'object', text: 'Զարթուցիչ' },
  { id: 'ai-189', category: 'object', text: 'Ֆեն' },
  { id: 'ai-190', category: 'object', text: 'Փոշեկուլ' },
  { id: 'ai-191', category: 'object', text: 'Պուլտ' },
  { id: 'ai-192', category: 'object', text: 'Փուչիկ' },
  { id: 'ai-193', category: 'object', text: 'Շրթներկ' },
  { id: 'ai-194', category: 'object', text: 'Պաղպաղակ' },
  { id: 'ai-195', category: 'object', text: 'Ձմերուկ' },
  { id: 'ai-196', category: 'object', text: 'Սպագետի' },
  { id: 'ai-197', category: 'object', text: 'Կիտրոն' },
  { id: 'ai-198', category: 'object', text: 'Մաստակ' },
  { id: 'ai-199', category: 'object', text: 'Շաուրմա' },
  { id: 'ai-200', category: 'object', text: 'Խցանում' },
];
